### ISSUE TITLE
Latest version won't start - syntax error re: highResAlbumArtUrl

### ISSUE THREAD

**Issue by rgraciano** [jishi/node-sonos-http-api#115]
$ git clone https://github.com/jishi/node-sonos-http-api.git nsham

$ npm install --production
npm WARN package.json sonos-http-api@0.17.0 No license field.
npm WARN engine require-fu@1.0.0: wanted: {"node":"0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN peerDependencies The peer dependency continuation-local-storage@~3 included from cls-bluebird will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

$ npm start
> node server.js

node_modules/sonos-discovery/lib/player.js:259
      .then((highResAlbumArtUrl) => {
                                 ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ryan/dev/nsham/node_modules/sonos-discovery/lib/sonos.js:11:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

**Comment by NovaGL** [comment]
You need to use node v4 or higher the new versions don't do node v0.12

**Comment by jishi** [comment]
What NovaGL said. You need to upgrade node to version 4 or higher.
