### ISSUE TITLE
fresh installation

### ISSUE THREAD

**Issue by bokila** [jishi/node-sonos-http-api#125]
so I decided to start from scratch here so a fresh Ubuntu 14.04 on a dell laptop and after some initial driver issues I ended up with a weird error 127 when starting npm, but that was fixed with some legacy fix that I found online but now I'm stuck with a weird error 8.... see below - any ideas

/var/sonos/sonos-http-api/node_modules/sonos-discovery/lib/player.js:259
      .then((highResAlbumArtUrl) => {
                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/sonos/sonos-http-api/node_modules/sonos-discovery/lib/sonos.js:11:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by jishi** [comment]
You need to make sure that you are running node 4+. Download and install it manually directly from nodejs.org.
