### ISSUE TITLE
TTS Fails on OSX 10.11

### ISSUE THREAD

**Issue by mauijim68** [jishi/node-sonos-http-api#130]
Node package was running on OS X as a test.  Tried to play a simple TTS using:

http://localhost:5005/say/Hello

Node package crashed, could not find server www.nerd.host:80 (tried to ping, failed to resolve using Comcast DNS). File created (mp3) was of 0 length.  Sonos zone had it as its current playlist but was stuck on it.

```
Cerberus:node-sonos-http-api-master pacyga$ npm start

> sonos-http-api@0.17.0 start /Users/pacyga/Public/node-sonos-http-api-master
> node server.js

no settings file found, will only use default settings
http server listening on port 5005
no preset file, ignoring...
Downloading new tts message file: /Users/pacyga/Public/node-sonos-http-api-master/static/tts/f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0-en.mp3
Using cached tts message file: f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0-en.mp3
Using cached tts message file: f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0-en.mp3
could not download file f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0-en.mp3 { [Error: getaddrinfo ENOTFOUND www.nerd.host www.nerd.host:80]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.nerd.host',
  host: 'www.nerd.host',
  port: 80 }
/Users/pacyga/Public/node-sonos-http-api-master/lib/actions/say.js:231
          fs.unlink(dest);
                    ^

ReferenceError: dest is not defined
    at ClientRequest.<anonymous> (/Users/pacyga/Public/node-sonos-http-api-master/lib/actions/say.js:231:21)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:998:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.17.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@0.17.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pacyga/Public/node-sonos-http-api-master/npm-debug.log
Cerberus:node-sonos-http-api-master pacyga$ ping www.nerd.host:80
ping: cannot resolve www.nerd.host:80: Unknown host
Cerberus:node-sonos-http-api-master pacyga$ ping www.nerd.host
ping: cannot resolve www.nerd.host: Unknown host
Cerberus:node-sonos-http-api-master pacyga$ 
```

**Comment by magnusrydin** [comment]
While waiting for the tts service used to be replaced, you can temporarily replace the current implementation with something that uses an existing free tts service, such as the one at http://www.voicerss.org/ . You can sing up for free to get the api key.

**Comment by mauijim68** [comment]
Cool! thanks!

**Comment by m0rph13** [comment]
So 
1. get a free account at http://www.voicerss.org/ (in order to get an API-key) 
 2. edit /lib/actions/say.js
and change the line where the URL to the TTS is specified to something like

`var tts_request = 'http://api.voicerss.org/?key=' + '<your API key>' + '&src=' + phrase + '&hl=' + language + '&f=' + '16khz_8bit_stereo';`

language is like international iso code but lowercased, as in "en-us" or "en-ca","sv-se" and so forth.

**Comment by m0rph13** [comment]
Oh, just spotted that this was already covered here:
https://github.com/jishi/node-sonos-http-api/issues/97

**Comment by jishi** [comment]
Yeah, I'm aware of the issue with the current TTS implementation. I will try and fix this as soon as possible. Follow https://github.com/jishi/node-sonos-http-api/issues/97 to receive update on progress. 

Closing.
