### ISSUE TITLE
Cannot start service

### ISSUE THREAD

**Issue by xinfinimanx** [jishi/node-sonos-http-api#135]
> sonos-http-api@0.17.0 start /Users/infiniman/Downloads/sonos API
> node server.js

/Users/infiniman/Downloads/sonos API/node_modules/sonos-discovery/lib/player.js:259
      .then((highResAlbumArtUrl) => {
                                 ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/infiniman/Downloads/sonos API/node_modules/sonos-discovery/lib/sonos.js:11:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.17.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@0.17.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/infiniman/Downloads/sonos API/npm-debug.log

**Comment by xinfinimanx** [comment]
[npm-debug.log.zip](https://github.com/jishi/node-sonos-http-api/files/101942/npm-debug.log.zip)

**Comment by jishi** [comment]
You are running node 0.12, you need to use node 4+ now.
