### ISSUE TITLE
all folders and files are loaded under action

### ISSUE THREAD

**Issue by jishi** [jishi/node-sonos-http-api#173]
@libatiba No worries, I create a ticket for you. Thank you for giving such detailed input. 

I did a little more testing…
The problem arrises in general when the lib/actions-folder contains a subdirectory that contains a file. An empty subdirectory does not provoke the error.
So it’s very easy for you to reproduce the error: just create a directory „test“ in lib/actions and copy a file into this folder.

On Synology Disk Station hidden folders are created by an indexing service. Every directory has a subdirectory named „@eaDir“ containing an index file for every file and folder with the naming convention: filename@SynoEAStream or foldername@SynoEAStream
These folders are always recreated when new files are copied in the directories. The @-sign at the beginnen of a folder-name does not generally hides them from the user. Only @eaDir -folders are hidden. If I rename the folder (on a ssh-Shell)
 to @eaTir (D->T) then the file is visible.  (I’m not a unix-professional - so I don’t now the mechanism how they do the hiding…) But your javascript sees them and the error ist caused. (on the ssh-Shell the ls-command shows the files, but any access to the
 directory with smb (Windows-Share) or afp (Apple, OSX) hides the directory)

From my understanding the error is caused in the file nodemodules/require-fu/lib/index.js  in function requirePath
(but I’m no javascript-expert too!)

In my opinion there are two ways to prevent the error:
1. prevent subdirectory search when enumerating objects in /lib/actions (no problem as long as never subdirectories are needed)
2. filter any subdirectories starting with the @-sign (It’s the synology-way of hiding files - if I remember correct it must not only be @eaDir but also @tmp, @ssbackup…)

Following is the output from my terminal (line numbers must not be correct since I added some console.log-entries to trace down the error)
 sonos-http-api@0.18.1 start /volume1/Data/node-sonos-http
 node server.js
no settings file found, will ooonly use default settings
info: binding SSDP to port 1905
info: discovering all IPs from lo
info: discovering all IPs from bond0
info: discovering all IPs from ppp300
info: relevant IPs 192.168.0.90=null, 10.2.0.0=null
Listening on
http://localhost:5007/
module.js:341
    throw err;
    ^

Error: Cannot find module '/volume1/Data/node-sonos-http/lib/actions/'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requirePath (/volume1/Data/node-sonos-http/node_modules/require-fu/lib/index.js:24:22)
    at /volume1/Data/node-sonos-http/node_modules/require-fu/lib/index.js:36:9
    at Array.forEach (native)
    at fuDirectory (/volume1/Data/node-sonos-http/node_modules/require-fu/lib/index.js:33:34)
    at /volume1/Data/node-sonos-http/node_modules/require-fu/lib/index.js:40:5
    at new HttpAPI (/volume1/Data/node-sonos-http/lib/sonos-http-api.js:42:24)
    at Object.<anonymous> (/volume1/Data/node-sonos-http/server.js:51:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm

ERR! Linux 3.10.35
npm

ERR!
argv "/usr/local/n/versions/node/5.8.0/bin/node" "/usr/local/n/versions/node/5.8.0/bin/npm" "start"
npm

ERR!
node v5.8.0
npm

ERR!
npm  v3.7.3
npm

ERR!
code ELIFECYCLE
npm

ERR! sonos-http-api@0.18.1 start: `node server.js`
npm

ERR! Exit status 1

npm
ERR! 
npm

ERR! Failed at the sonos-http-api@0.18.1 start script 'node server.js'.
npm

ERR! Make sure you have the latest version of node.js and npm installed.
npm

ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm

ERR! not with npm itself.
npm

ERR! Tell the author that this fails on your system:
npm

ERR!     node server.js
npm

ERR! You can get information on how to open an issue for this project with:
npm

ERR!     npm bugs sonos-http-api
npm

ERR! Or if that isn't available, you can get their info via:
npm

ERR!     npm owner ls sonos-http-api
npm

ERR! There is likely additional logging output above.

npm

ERR! Please include the following file with any support request:
npm

ERR!     /volume1/Data/node-sonos-http/npm-debug.log

Hopefully me error-description is detailed enough for you to reproduce, find and fix it!

**Comment by jishi** [comment]
The new beta uses a different file loader and will omit all files mentioned here. That means:

ignores folders
ignores files starting with "."
ignores files not ending in .js
