### ISSUE TITLE
Can't restart server once server has stopped once

### ISSUE THREAD

**Issue by kenibarwick** [jishi/node-sonos-http-api#203]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.9
3 info using node@v4.4.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sonos-http-api@0.19.0~prestart: sonos-http-api@0.19.0
6 silly lifecycle sonos-http-api@0.19.0~prestart: no script for prestart, continuing
7 info lifecycle sonos-http-api@0.19.0~start: sonos-http-api@0.19.0
8 verbose lifecycle sonos-http-api@0.19.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle sonos-http-api@0.19.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mediacenter/Documents/node-sonos-http-api/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle sonos-http-api@0.19.0~start: CWD: /Users/mediacenter/Documents/node-sonos-http-api
11 silly lifecycle sonos-http-api@0.19.0~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle sonos-http-api@0.19.0~start: Returned: code: 1  signal: null
13 info lifecycle sonos-http-api@0.19.0~start: Failed to exec start script
14 verbose stack Error: sonos-http-api@0.19.0 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid sonos-http-api@0.19.0
16 verbose cwd /Users/mediacenter/Documents/node-sonos-http-api
17 error Darwin 15.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.4.4
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error sonos-http-api@0.19.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the sonos-http-api@0.19.0 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sonos-http-api package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sonos-http-api
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sonos-http-api
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kenibarwick** [comment]
works by running node server.js
