### ISSUE TITLE
Failed to handle error while fetching favorites

### ISSUE THREAD

**Issue by gnachman** [jishi/node-sonos-http-api#234]
I visited the /favorites URL and got an exception:

````
/Users/gnachman/git/node-sonos-http-api/lib/actions/favorites.js:13
    favorites.forEach(function (i) {
             ^

TypeError: Cannot read property 'forEach' of undefined
    at /Users/gnachman/git/node-sonos-http-api/lib/actions/favorites.js:13:14
    at /Users/gnachman/git/node-sonos-http-api/node_modules/sonos-discovery/lib/player.js:769:7
    at /Users/gnachman/git/node-sonos-http-api/node_modules/sonos-discovery/lib/player.js:717:7
    at ClientRequest.<anonymous> (/Users/gnachman/git/node-sonos-http-api/node_modules/sonos-discovery/lib/player.js:498:9)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:359:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
````

It looks like `favorites.js` does not handle the error case at all.

````
  player.getFavorites(function (error, favorites) {

    if (values[0] === 'detailed') {
      callback(favorites);
      return;
    }

    // only present relevant data
    var simpleFavorites = [];
    favorites.forEach(function (i) {
      simpleFavorites.push(i.title);
    });
    callback(simpleFavorites);
  });
````

It looks like playlists.js has the same issue.

**Comment by jishi** [comment]
Could you please test the beta version (checkout beta branch or download the zip for beta branch https://github.com/jishi/node-sonos-http-api/archive/beta.zip) and see if the problem still exist? 

The beta has a lot of improvements and is basically on-pair with the current version in terms of functionality.

**Comment by gnachman** [comment]
The beta version works like a charm. 👍
