### ISSUE TITLE
node vs nodejs

### ISSUE THREAD

**Issue by ironlion27** [jishi/node-sonos-http-api#237]
on npm start

```
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"

```

**Comment by jishi** [comment]
You have installed node.js via debian apt, right? Not sure why this error would occur, but ehtier start it manually (without npm) with `nodejs server.js` or install the official binaries for node.js and remove the apt one.

**Comment by ironlion27** [comment]
Yes, got from apt.  When running `nodejs server.js` I get this error:

> /home/zeus/node-sonos-http-api/node_modules/sonos-discovery/lib/player.js:279
      .then((highResAlbumArtUrl) => {
                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/zeus/node-sonos-http-api/node_modules/sonos-discovery/lib/sonos.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by jishi** [comment]
Then the version from apt is to old. You need at least node 4.0.0 or
higher, I suggest you install node manually.

**Comment by ironlion27** [comment]
installed newest version of node but can't figure out how to get rid of the old one.  added the new node to $PATH so shouldn't be too much of an issue I guess.

**Comment by jishi** [comment]
You should be able to just use apt-get remove nodejs
