### ISSUE TITLE
Beta / sleep command

### ISSUE THREAD

**Issue by lukehoverman** [jishi/node-sonos-http-api#262]
I am really enjoying the beta and the updated sayall possibilities. Thank you.

I did notice that the sleep command was not working for me. Below are the various responses I get:

http://local.host:5005/kitchen/sleep/off

_Works perfectly by slowly fading until fully stopped_

http://local.host:5005/kitchen/sleep/60

_Node crashes with no error messages_

http://local.host:5005/kitchen/sleep/11:11:11

Error: Internal Server Error
    at ClientRequest.<anonymous> (/home/pi/sonos/node-sonos-http-api-beta/node_modules/sonos-discovery/lib/helpers/request.js:22:21)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:309:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:529:20)
undefined

**Comment by jishi** [comment]
Fixed in latest version
