### ISSUE TITLE
setavtransporturi/x-file-cifs not working

### ISSUE THREAD

**Issue by Home-Control9000** [jishi/node-sonos-http-api#273]
Hi,

I installed latest beta. I try to play mp3 from a cifs server:
curl http://linux7:5005/woonkamer/setavtransporturi/x-file-cifs%f2%f2linux7.local%f2mpdshare%f2sonos%f2play1.mp3

server.js is crashing and i get the message:

 return player.setAVTransportURI(decodeURIComponent(values[0]));
           ^
**URIError: URI malformed**
    at decodeURIComponent (native)
    at Object.setAVTransportURI (/usr/local/home-control/node-sonos-http-api-beta/lib/actions/setavtransporturi.js:2:35)
    at handleAction (/usr/local/home-control/node-sonos-http-api-beta/lib/sonos-http-api.js:102:35)
    at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/usr/local/home-control/node-sonos-http-api-beta/lib/sonos-http-api.js:79:5)
    at /usr/local/home-control/node-sonos-http-api-beta/server.js:80:13
    at Server.finish (/usr/local/home-control/node-sonos-http-api-beta/node_modules/node-static/lib/node-static.js:111:13)
    at finish (/usr/local/home-control/node-sonos-http-api-beta/node_modules/node-static/lib/node-static.js:170:14)
    at /usr/local/home-control/node-sonos-http-api-beta/node_modules/node-static/lib/node-static.js:178:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by jishi** [comment]
%f2 doesn't look correct. Is it a slash you want to represent? slash is %2f, not %f2 :)

**Comment by Home-Control9000** [comment]
Hi Jimmy,

You are right, i found it myself a few minutes ago:) with the %2f:
Im using now the right urlencode but still no succes:
curl http://linux7:5005/woonkamer/setavtransporturi/http%3A%2F%2F192.168.1.48%3A5005%2Fplay1.mp3

i get the following message: 
/usr/local/home-control/node-sonos-http-api-beta/lib/actions/setavtransporturi.js:2
  return player.setAVTransportURI(decodeURIComponent(values[0]));
                ^

**TypeError: player.setAVTransportURI is not a function**
    at Object.setAVTransportURI (/usr/local/home-control/node-sonos-http-api-beta/lib/actions/setavtransporturi.js:2:17)
    at handleAction (/usr/local/home-control/node-sonos-http-api-beta/lib/sonos-http-api.js:102:35)
    at HttpAPI.requireDir.requestHandler.handleAction.then [as requestHandler] (/usr/local/home-control/node-sonos-http-api-beta/lib/sonos-http-api.js:79:5)
    at /usr/local/home-control/node-sonos-http-api-beta/server.js:80:13
    at Server.finish (/usr/local/home-control/node-sonos-http-api-beta/node_modules/node-static/lib/node-static.js:111:13)
    at finish (/usr/local/home-control/node-sonos-http-api-beta/node_modules/node-static/lib/node-static.js:170:14)
    at /usr/local/home-control/node-sonos-http-api-beta/node_modules/node-static/lib/node-static.js:144:17
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by jishi** [comment]
Well, that's an unfortunate bug, I have changed the method name, in the discovery lib. I just pushed an update that fixes it!

**Comment by Home-Control9000** [comment]
Hi Jimmy,

That was the solution!
Thanks for you quick reply. 

Walter
