### ISSUE TITLE
Error setting preset when favorite is already assigned

### ISSUE THREAD

**Issue by ckuehl** [jishi/node-sonos-http-api#288]
My presets.json file is as follows:

```
{
	"all": {
		"players": [
			{
				"roomName": "Study",
				"volume": 10
			},
			{
				"roomName": "Kitchen",
				"volume": 5
			}
		],
		"favorite": "Pandora Country"
	}
}
```

If I have a different station playing on `Study` and invoke the preset everything works as expected. If instead, the `Pandora Country` favorite is already assigned to `Study`, I get the following error:

```
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/Users/ckuehl/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:87:10)\n    at Player.setAVTransport (/Users/ckuehl/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:621:15)\n    at /Users/ckuehl/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithFavorite.js:40:19\n    at process._tickCallback (node.js:401:9)"}
```

Console logs with the debug flag enabled show:

```
2016-09-05T17:38:07.307Z DEBUG coordinator is Study
2016-09-05T17:38:07.308Z DEBUG skipping grouping for Kitchen because it is already grouped with coordinator
2016-09-05T17:38:07.308Z DEBUG setting volume 10 on Study
2016-09-05T17:38:07.326Z DEBUG setting volume 5 on Kitchen
2016-09-05T17:38:07.352Z DEBUG replacing with favorite Pandora Country
2016-09-05T17:38:07.389Z DEBUG found favorites
  [ 'Adele',
  'Pandora Country',
  'Smooth Jazz Radio' ]
2016-09-05T17:38:07.390Z DEBUG favorite is radiostation
2016-09-05T17:38:07.390Z DEBUG setting AVTransport to pndrradio:3113573328055096624?sn=1 with metadata <DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="OXOX3113573328055096624" parentID="0" restricted="true"><dc:title>Today&apos;s Country Radio</dc:title><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3_redacted</desc></item></DIDL-Lite>
2016-09-05T17:38:07.399Z ERROR
  Error
    at Object.invoke (/Users/ckuehl/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:87:10)
    at Player.setAVTransport (/Users/ckuehl/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:621:15)
    at /Users/ckuehl/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithFavorite.js:40:19
    at process._tickCallback (node.js:401:9)
```

**Comment by jishi** [comment]
Sounds like you are suffering from this underlying bug in Sonos:

https://github.com/jishi/node-sonos-http-api/issues/159

I might be able to avoid setting the same uri since I would know which is already loaded, to try and mitigate it. I just assumed that this was not really an issue, but I guess it becomes a bigger issue when you are using presets like this.

**Comment by ckuehl** [comment]
@jishi Thanks for making the correlation. I'd appreciate anything you can do to work around this issue so that I don't have to work around it on the consumer side.

**Comment by jishi** [comment]
I think I've fixed it now with beta.21 version. Update and see if it fixes it.

**Comment by ckuehl** [comment]
@jishi It's working great now. Thanks!
