### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by noesberger** [jishi/node-sonos-http-api#289]
I just pulled the newest version and after an npm install I can't start the server anymore. I'm getting all the time the following error:

/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:151
      if (property.$text.indexOf('Q:0') !== -1) {
                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at EventEmitter.<anonymous> (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:151:25)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at SAXStream.onCloseTag (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/lib/xml-flow.js:131:15)
    at emitOne (events.js:77:13)
    at SAXStream.emit (events.js:169:7)
    at Object.me._parser.(anonymous function) [as onclosetag] (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:258:17)
    at emit (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:1449:13)
    at SAXStream.write (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:239:18)
    at IncomingMessage.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:360:10)

**Comment by jishi** [comment]
Hm, that is a new one. Could you start the server with the following:

`NODE_LOG_LEVEL=trace node server.js`

And try and reproduce it? Seems like your system or state doesn't send back the expected data that I'm seeing. Trace logging will output the XML sent from the player (that I'm trying to parse).

**Comment by noesberger** [comment]
2016-09-07T08:59:44.766Z TRACE <ZoneGroups><ZoneGroup Coordinator="RINCON_000E5881D97C01400" ID="RINCON_000E5881D97C01400:80"><ZoneGroupMember UUID="RINCON_000E5881D97C01400" Location="http://192.168.1.104:1400/xml/device_description.xml" ZoneName="Spielecke_OG" Icon="x-rincon-roomicon:living" Configuration="1" SoftwareVersion="32.11-30071" MinCompatibleVersion="31.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="99" WirelessMode="0" WirelessLeafOnly="0" HasConfiguredSSID="0" ChannelFreq="2462" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" SonarState="4"/></ZoneGroup><ZoneGroup Coordinator="RINCON_B8E937B74F7E01400" ID="RINCON_B8E937B74F7E01400:36"><ZoneGroupMember UUID="RINCON_B8E937B74F7E01400" Location="http://192.168.1.107:1400/xml/device_description.xml" ZoneName="Nico" Icon="x-rincon-roomicon:playroom" Configuration="1" SoftwareVersion="32.11-30071" MinCompatibleVersion="31.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="29" WirelessMode="0" WirelessLeafOnly="0" HasConfiguredSSID="0" ChannelFreq="2462" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" SonarState="4"/></ZoneGroup><ZoneGroup Coordinator="RINCON_5CAAFD1AD99101400" ID="RINCON_5CAAFD1AD99101400:1155"><ZoneGroupMember UUID="RINCON_5CAAFD1AD99101400" Location="http://192.168.1.108:1400/xml/device_description.xml" ZoneName="Wohnzimmer" Icon="x-rincon-roomicon:living" Configuration="1" SoftwareVersion="32.11-30071" MinCompatibleVersion="31.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="19" WirelessMode="0" WirelessLeafOnly="0" HasConfiguredSSID="0" ChannelFreq="2462" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" SonarState="4"/></ZoneGroup><ZoneGroup Coordinator="RINCON_B8E93787C70201400" ID="RINCON_B8E93787C70201400:40"><ZoneGroupMember UUID="RINCON_B8E93787C70201400" Location="http://192.168.1.118:1400/xml/device_description.xml" ZoneName="Fabio" Icon="x-rincon-roomicon:masterbedroom" Configuration="1" SoftwareVersion="32.11-30071" MinCompatibleVersion="31.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="32" WirelessMode="0" WirelessLeafOnly="0" HasConfiguredSSID="0" ChannelFreq="2462" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" SonarState="4"/></ZoneGroup></ZoneGroups>
2016-09-07T08:59:45.089Z TRACE <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/"><InstanceID val="0"><TransportState val="STOPPED"/><CurrentPlayMode val="NORMAL"/><CurrentCrossfadeMode val="0"/><NumberOfTracks val="4"/><CurrentTrack val="1"/><CurrentSection val="0"/><CurrentTrackURI val="aac://stream.srg-ssr.ch/m/drs3/aacp_96"/><CurrentTrackDuration val="0:00:00"/><CurrentTrackMetaData val="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;-1&quot; parentID=&quot;-1&quot; restricted=&quot;true&quot;&gt;&lt;res protocolInfo=&quot;sonos.com-http:*:application/octet-stream:*&quot;&gt;x-sonosapi-stream:s15147?sid=254&amp;amp;flags=8224&amp;amp;sn=0&lt;/res&gt;&lt;r:streamContent&gt;&lt;/r:streamContent&gt;&lt;r:radioShowMd&gt;&lt;/r:radioShowMd&gt;&lt;upnp:albumArtURI&gt;/getaa?s=1&amp;amp;u=x-sonosapi-stream%3as15147%3fsid%3d254%26flags%3d8224%26sn%3d0&lt;/upnp:albumArtURI&gt;&lt;dc:title&gt;x-sonosapi-stream:s15147?sid=254&amp;amp;flags=8224&amp;amp;sn=0&lt;/dc:title&gt;&lt;upnp:class&gt;object.item&lt;/upnp:class&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;"/><r:NextTrackURI val=""/><r:NextTrackMetaData val=""/><r:EnqueuedTransportURI val="x-sonosapi-stream:s15147?sid=254&amp;flags=8224&amp;sn=0"/><r:EnqueuedTransportURIMetaData val="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;-1&quot; parentID=&quot;-1&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;SRF 3&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON65031_&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;"/><PlaybackStorageMedium val="NETWORK"/><AVTransportURI val="x-sonosapi-stream:s15147?sid=254&amp;flags=8224&amp;sn=0"/><AVTransportURIMetaData val="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;-1&quot; parentID=&quot;-1&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;SRF 3&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON65031_&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;"/><NextAVTransportURI val=""/><NextAVTransportURIMetaData val=""/><CurrentTransportActions val="Set, Stop, Play"/><r:CurrentValidPlayModes val=""/><r:MuseSessions val=""/><TransportStatus val="OK"/><r:SleepTimerGeneration val="0"/><r:AlarmRunning val="0"/><r:SnoozeRunning val="0"/><r:RestartPending val="0"/><TransportPlaySpeed val="NOT_IMPLEMENTED"/><CurrentMediaDuration val="NOT_IMPLEMENTED"/><RecordStorageMedium val="NOT_IMPLEMENTED"/><PossiblePlaybackStorageMedia val="NONE, NETWORK"/><PossibleRecordStorageMedia val="NOT_IMPLEMENTED"/><RecordMediumWriteStatus val="NOT_IMPLEMENTED"/><CurrentRecordQualityMode val="NOT_IMPLEMENTED"/><PossibleRecordQualityModes val="NOT_IMPLEMENTED"/></InstanceID></Event>
2016-09-07T08:59:45.234Z TRACE RINCON_5CAAFD1AD99101400,10
2016-09-07T08:59:45.240Z TRACE RINCON_5CAAFD1AD99101400,126
/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:151
      if (property.$text.indexOf('Q:0') !== -1) {
                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at EventEmitter.<anonymous> (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:151:25)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at SAXStream.onCloseTag (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/lib/xml-flow.js:131:15)
    at emitOne (events.js:77:13)
    at SAXStream.emit (events.js:169:7)
    at Object.me._parser.(anonymous function) [as onclosetag] (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:258:17)
    at emit (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:1449:13)
    at SAXStream.write (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:239:18)
    at IncomingMessage.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:360:10)

**Comment by noesberger** [comment]
Can you see my "full" comment? Because in the edit mode I have more data, than what is shown on the page.

**Comment by jishi** [comment]
I can see the XML if I edit your post, I'll look into it!

**Comment by noesberger** [comment]
OK, thanks.

**Comment by jplourde5** [comment]
I'm getting a similar error on startup.  I've betting getting it with the new master from the start, but it doesn't seem to hurt anything. Guessing that it might have to do with having no presets.

TypeError: Cannot read property 'startsWith' of undefined
    at parseAVTransportMetadata.then.radioInfo (/Users/tplourdes/Dropbox/Home/NodeApps/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:249:47)
    at process._tickCallback (internal/process/next_tick.js:103:7) 'TypeError: Cannot read property \'startsWith\' of undefined\n    at parseAVTransportMetadata.then.radioInfo (/Users/tplourdes/Dropbox/Home/NodeApps/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:249:47)\n    at process._tickCallback (internal/process/next_tick.js:103:7)'

**Comment by jplourde5** [comment]
For my problem it appears that the issue is that not every track has an albumArtUri.  This is the offending entry.  Line In appears to be the culprit.

currentTrack = {"title":"Master Bed TV","duration":0,"uri":"x-rincon-stream:RINCON_000E5820E1DA01400","type":"line_in"}

**Comment by cwook** [comment]
I also have this issue. This is a first-time setup for me. I'm running the server on Minibian.

```
cwook@minibian:~/node_modules/sonos-http-api$ NODE_LOG_LEVEL=trace node server.js
no settings file found, will only use default settings
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
2016-09-11T02:23:45.306Z TRACE sending M-SEARCH...
http server listening on port 5005
no preset file, ignoring...
2016-09-11T02:23:45.807Z TRACE <ZoneGroups><ZoneGroup Coordinator="RINCON_000E583EB2C201400" ID="RINCON_000E583EB2C201400:19"><ZoneGroupMember UUID="RINCON_000E583EB2C201400" Location="http://10.0.0.80:1400/xml/device_description.xml" ZoneName="Kitchen" Icon="x-rincon-roomicon:kitchen" Configuration="1" SoftwareVersion="33.15-32291" MinCompatibleVersion="32.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="44" WirelessMode="1" WirelessLeafOnly="0" HasConfiguredSSID="1" ChannelFreq="2412" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" RoomCalibrationState="4"/></ZoneGroup><ZoneGroup Coordinator="RINCON_000E583E944801400" ID="RINCON_000E583E944801400:15"><ZoneGroupMember UUID="RINCON_000E583E944801400" Location="http://10.0.0.78:1400/xml/device_description.xml" ZoneName="Living Room" Icon="x-rincon-roomicon:living" Configuration="1" SoftwareVersion="33.15-32291" MinCompatibleVersion="32.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="37" WirelessMode="1" WirelessLeafOnly="0" HasConfiguredSSID="1" ChannelFreq="2412" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" RoomCalibrationState="4"/></ZoneGroup><ZoneGroup Coordinator="RINCON_000E583E7ADA01400" ID="RINCON_000E583E7ADA01400:14"><ZoneGroupMember UUID="RINCON_000E583E7ADA01400" Location="http://10.0.0.160:1400/xml/device_description.xml" ZoneName="Living Room Deck" Icon="x-rincon-roomicon:living" Configuration="1" SoftwareVersion="33.15-32291" MinCompatibleVersion="32.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="36" WirelessMode="1" WirelessLeafOnly="0" HasConfiguredSSID="1" ChannelFreq="2412" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" RoomCalibrationState="4"/></ZoneGroup><ZoneGroup Coordinator="RINCON_000E583E943601400" ID="RINCON_000E583E943601400:14"><ZoneGroupMember UUID="RINCON_000E583E943601400" Location="http://10.0.0.60:1400/xml/device_description.xml" ZoneName="Family Room Deck" Icon="x-rincon-roomicon:playroom" Configuration="1" SoftwareVersion="33.15-32291" MinCompatibleVersion="32.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="36" WirelessMode="1" WirelessLeafOnly="0" HasConfiguredSSID="1" ChannelFreq="2412" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" RoomCalibrationState="4"/></ZoneGroup><ZoneGroup Coordinator="RINCON_000E583E95DC01400" ID="RINCON_000E583E95DC01400:10"><ZoneGroupMember UUID="RINCON_000E583E95DC01400" Location="http://10.0.0.54:1400/xml/device_description.xml" ZoneName="Nook" Icon="x-rincon-roomicon:living" Configuration="1" SoftwareVersion="33.15-32291" MinCompatibleVersion="32.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="36" WirelessMode="1" WirelessLeafOnly="0" HasConfiguredSSID="1" ChannelFreq="2412" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" RoomCalibrationState="4"/></ZoneGroup><ZoneGroup Coordinator="RINCON_000E583E8DD801400" ID="RINCON_000E583E8DD801400:20"><ZoneGroupMember UUID="RINCON_000E583E8DD801400" Location="http://10.0.0.166:1400/xml/device_description.xml" ZoneName="Family Room" Icon="x-rincon-roomicon:family" Configuration="1" SoftwareVersion="33.15-32291" MinCompatibleVersion="32.0-00000" LegacyCompatibleVersion="25.0-00000" BootSeq="40" WirelessMode="1" WirelessLeafOnly="0" HasConfiguredSSID="1" ChannelFreq="2412" BehindWifiExtender="0" WifiEnabled="1" Orientation="0" RoomCalibrationState="4"/></ZoneGroup></ZoneGroups>
2016-09-11T02:23:46.286Z TRACE RINCON_000E583E7ADA01400,0
2016-09-11T02:23:46.294Z TRACE RINCON_000E583E7ADA01400,0
2016-09-11T02:23:46.359Z TRACE RINCON_000E583E7ADA01400,0
2016-09-11T02:23:46.377Z TRACE RINCON_000E583E7ADA01400,0
2016-09-11T02:23:46.411Z TRACE RINCON_000E583E7ADA01400,0
2016-09-11T02:23:46.416Z TRACE RINCON_000E583E7ADA01400,0
2016-09-11T02:23:46.450Z TRACE RINCON_000E583E7ADA01400,0
2016-09-11T02:23:46.465Z TRACE RINCON_000E583E7ADA01400,0
/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:151
      if (property.$text.indexOf('Q:0') !== -1) {
                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at EventEmitter.<anonymous> (/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:151:25)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at SAXStream.onCloseTag (/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/lib/xml-flow.js:131:15)
    at emitOne (events.js:77:13)
    at SAXStream.emit (events.js:169:7)
    at Object.me._parser.(anonymous function) [as onclosetag] (/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:258:17)
    at emit (/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:1449:13)
    at SAXStream.write (/home/cwook/node_modules/sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:239:18)
    at IncomingMessage.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
```

**Comment by jishi** [comment]
Test the latest version, it should fix this issue

**Comment by noesberger** [comment]
With the new version it's working fine. I'm also able to play playlists and favorites from the presets.json file.
