### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by finish06** [jishi/node-sonos-http-api#296]
Here is the log output...
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.7
3 info using node@v4.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sonos-http-api@1.0.0-beta.21~prestart: sonos-http-api@1.0.0-beta.21
6 silly lifecycle sonos-http-api@1.0.0-beta.21~prestart: no script for prestart, continuing
7 info lifecycle sonos-http-api@1.0.0-beta.21~start: sonos-http-api@1.0.0-beta.21
8 verbose lifecycle sonos-http-api@1.0.0-beta.21~start: unsafe-perm in lifecycle true
9 verbose lifecycle sonos-http-api@1.0.0-beta.21~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/trek/sonos/node_modules/.bin:/usr/local$
10 verbose lifecycle sonos-http-api@1.0.0-beta.21~start: CWD: /home/trek/sonos
11 silly lifecycle sonos-http-api@1.0.0-beta.21~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle sonos-http-api@1.0.0-beta.21~start: Returned: code: 1  signal: null
13 info lifecycle sonos-http-api@1.0.0-beta.21~start: Failed to exec start script
14 verbose stack Error: sonos-http-api@1.0.0-beta.21 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid sonos-http-api@1.0.0-beta.21
16 verbose cwd /home/trek/sonos
17 error Linux 4.4.0-36-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.5.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error sonos-http-api@1.0.0-beta.21 start: `node server.js`
22 error Exit status 1
23 error Failed at the sonos-http-api@1.0.0-beta.21 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sonos-http-api package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sonos-http-api
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sonos-http-api
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by finish06** [comment]
I see you wanted the log level increased in a previous issue.  Would you like that information also?
```NODE_LOG_LEVEL=trace node server.js``` -> correct statement?

**Comment by jishi** [comment]
Did you get any error when doing the `npm install`?

**Comment by finish06** [comment]
It appears that as long as I don't update npm via ``` sudo npm install -g npm``` .... I don't have any issues with version 3.10.6... however 3.10.7 was causing me issues.... Just a heads up as I believe 3.10.7 is the most current.  I will try to install it in another VM to see if I can mimic the issues and post them here.  Thanks for your awesome work on this project!  It is great.
