### ISSUE TITLE
Error: Cannot find module '../../settings.json'

### ISSUE THREAD

**Issue by firecold100** [jishi/node-sonos-http-api#298]
Hi. 

I encountered this issue in the new version of the project and now I cannot run it:

```
$ npm start

> sonos-http-api@1.0.0-beta.21 start /home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api
> node server.js

no settings file found, will only use default settings
module.js:327
    throw err;
    ^

Error: Cannot find module '../../settings.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/lib/actions/pandora.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/lib/helpers/require-dir.js:18:8
    at Array.forEach (native)
    at module.exports.files.map.filter (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/lib/sonos-http-api.js:42:3)
    at Object.<anonymous> (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/server.js:43:11)

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.0.0-beta.21 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.0.0-beta.21 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/npm-debug.log
```

**Comment by jishi** [comment]
I have fixed that now, please update and try again.

**Comment by firecold100** [comment]
Thanks! But now says this:

`$ npm start

> sonos-http-api@1.0.0-beta.21 start /home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api
> node server.js

no settings file found, will only use default settings
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
http server listening on port 5005
no preset file, ignoring...
/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:151
      if (property.$text.indexOf('Q:0') !== -1) {
                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at EventEmitter.<anonymous> (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:151:25)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at SAXStream.onCloseTag (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/lib/xml-flow.js:131:15)
    at emitOne (events.js:77:13)
    at SAXStream.emit (events.js:169:7)
    at Object.me._parser.(anonymous function) [as onclosetag] (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:258:17)
    at emit (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:1449:13)
    at SAXStream.write (/home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/node_modules/sonos-discovery/node_modules/xml-flow/node_modules/sax/lib/sax.js:239:18)
    at IncomingMessage.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.0.0-beta.21 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.0.0-beta.21 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/systmatic03/Documents/Github/django_automation/wisehome/nodejs/node-sonos-http-api/npm-debug.log
`

**Comment by NikoS34** [comment]
Hi,

it seems to be something next for me with the last update :

admin@DiskStation:~/DEV/node-sonos-http-api-master$ npm start

> sonos-http-api@1.0.1 start /volume1/homes/admin/DEV/node-sonos-http-api-master
> node server.js

2016-10-14T13:24:54.320Z INFO no settings file found, will only use default settings
2016-10-14T13:24:55.398Z INFO Presets loaded: { example:
   { players:
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'My example favorite' },
  presets:
   { players:
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Library', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'My example favorite' } }
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND' }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5005
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Object.<anonymous> (/volume1/homes/admin/DEV/node-sonos-http-api-master/server.js:113:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 3.10.77
npm ERR! argv "/volume1/@appstore/Node.js_v4/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.0.1 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /volume1/homes/admin/DEV/node-sonos-http-api-master/npm-debug.log

Thanks for your advice,
Nicolas

**Comment by NikoS34** [comment]
Solved !

On Synology port 5005 is used by WebDAV server (and that server seems to start by default in DSM 6).
I stopped it in the packet manager and now all is running.

-
Nicolas

**Comment by jishi** [comment]
It's possible to configure which port the http-api in settings.json.

**Comment by NikoS34** [comment]
Thanx jishi for your reply.

And moreover I've just add a voiceRSS API in that settings.json and that rules !
-
Nicolas
