### ISSUE TITLE
Not compatible with node 6.6.0

### ISSUE THREAD

**Issue by naixra** [jishi/node-sonos-http-api#339]
Hello,

Hello, after updating my Node system, Sonos Http Api always work so I'm doubted anything. Once I had a restart, when I tried to restart the server via the command node server.js, I got the following error :

`info: relevant IPs 192.168.1.25=null
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Object.<anonymous> (/home/medianucenter/node-sonos-http-api/lib/actions/say.js:11:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at requirePath (/home/medianucenter/node-sonos-http-api/node_modules/require-fu/lib/index.js:14:22)
    at /home/medianucenter/node-sonos-http-api/node_modules/require-fu/lib/index.js:21:9
    at Array.forEach (native)
    at fuDirectory (/home/medianucenter/node-sonos-http-api/node_modules/require-fu/lib/index.js:20:34)
    at /home/medianucenter/node-sonos-http-api/node_modules/require-fu/lib/index.js:25:5 code: 'MODULE_NOT_FOUND' }
info: notification server listening on port 3500
http server listening on port 5005
no preset file, ignoring...
info: scanning for players in ip 192.168.1.25
info: subscribing to topology 192.168.1.22
info: using local endpoint 192.168.1.25`

I learned later that it was perhaps not compatible with my version of Node, is there a fix to redo work?

Thanks.

**Comment by jishi** [comment]
The old version that you are running is probably not compatible with node 6. It's the require-fu module that seems to act out, for unknown reasons. In the new version (1.0.1) I no longer use that and I have tested it with node 6 and haven't found a problem yet. It is also significantly improved (although some if the features have been modified).

I suggest you install the new version in a new folder and test it out https://github.com/jishi/node-sonos-http-api/releases 

It also has a much improved preset loading where you have one file per preset instead, and auto-reloading when changing the presets. I suggest you switch to that. Do note that there is a slight change to the preset format (especially for "repeat").

**Comment by naixra** [comment]
Thanks you for your answer,

How can I install the new version 1.0.1. I clicked on your link and I got source code or sonos-http-api-1.0.1.img.gz. I don’t know how can I replace my older version on my NUC with Ubuntu by this newer.

best regards.

-- 
Miscellaneous
Sent with Airmail

Activé 11 octobre 2016 à 11:23:19, Jimmy Shimizu (notifications@github.com) a écrit:

The old version that you are running is probably not compatible with node 6. It's the require-fu module that seems to act out, for unknown reasons. In the new version (1.0.1) I no longer use that and I have tested it with node 6 and haven't found a problem yet. It is also significantly improved (although some if the features have been modified).

I suggest you install the new version in a new folder and test it out https://github.com/jishi/node-sonos-http-api/releases

It also has a much improved preset loading where you have one file per preset instead, and auto-reloading when changing the presets. I suggest you switch to that. Do note that there is a slight change to the preset format (especially for "repeat").

**Comment by jishi** [comment]
Do this:

Make sure the old sonos-http-api is not running. Move to the directory where you want the new install folder to be created.

`wget https://github.com/jishi/node-sonos-http-api/archive/v1.0.1.tar.gz`
`tar -zxf v1.0.1.tar.gz`
`cd node-sonos-http-api-1.0.1`
`npm install --production`
`npm start`

You should now run v1.0.1. Migrate your relevant configuration from the old installation into this one (presets, settings.json etc).

**Comment by naixra** [comment]
When I follow this I get : 

`> sonos-http-api@1.0.1 start /home/medianucenter/node-sonos-http-api-1.0.1
> node server.js

2016-10-11T09:48:08.932Z INFO no settings file found, will only use default settings
2016-10-11T09:48:09.374Z INFO Presets loaded: { example: 
   { players: 
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'My example favorite' } }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Object.<anonymous> (/home/medianucenter/node-sonos-http-api-1.0.1/lib/helpers/try-download-tts.js:11:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/medianucenter/node-sonos-http-api-1.0.1/lib/actions/say_v2.js:7:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Object.<anonymous> (/home/medianucenter/node-sonos-http-api-1.0.1/lib/actions/say_v2.js:17:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at files.map.filter.forEach (/home/medianucenter/node-sonos-http-api-1.0.1/lib/helpers/require-dir.js:18:8)
    at Array.forEach (native)
    at module.exports (/home/medianucenter/node-sonos-http-api-1.0.1/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/medianucenter/node-sonos-http-api-1.0.1/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/home/medianucenter/node-sonos-http-api-1.0.1/server.js:44:11) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Object.<anonymous> (/home/medianucenter/node-sonos-http-api-1.0.1/lib/actions/sayall.js:11:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at files.map.filter.forEach (/home/medianucenter/node-sonos-http-api-1.0.1/lib/helpers/require-dir.js:18:8)
    at Array.forEach (native)
    at module.exports (/home/medianucenter/node-sonos-http-api-1.0.1/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/medianucenter/node-sonos-http-api-1.0.1/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/home/medianucenter/node-sonos-http-api-1.0.1/server.js:44:11) code: 'MODULE_NOT_FOUND' }
2016-10-11T09:48:09.430Z INFO http server listening on port 5005
`

**Comment by jishi** [comment]
Looks like it starts up okay. The errors are merely warnings because you don't have a settings.json file. Do a 

`echo {} > settings.json`

in the node-sonos-http-api-1.0.1 folder to create an empty settings file to mute those errors.

**Comment by naixra** [comment]
Ok, there is not error anymore when I launch npm start in node-soon-http-api folder.

However, when I want to play on speaker in room with http request I get this error : 

http://192.168.1.25:5005/Chambre/play

`{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/home/medianucenter/node-sonos-http-api-1.0.1/node_modules/sonos-discovery/lib/helpers/soap.js:94:10)\n    at Player.play (/home/medianucenter/node-sonos-http-api-1.0.1/node_modules/sonos-discovery/lib/models/Player.js:379:15)\n    at Object.play (/home/medianucenter/node-sonos-http-api-1.0.1/lib/actions/playpause.js:11:28)\n    at handleAction (/home/medianucenter/node-sonos-http-api-1.0.1/lib/sonos-http-api.js:110:35)\n    at HttpAPI.requestHandler (/home/medianucenter/node-sonos-http-api-1.0.1/lib/sonos-http-api.js:87:5)\n    at /home/medianucenter/node-sonos-http-api-1.0.1/server.js:80:13\n    at Server.finish (/home/medianucenter/node-sonos-http-api-1.0.1/node_modules/node-static/lib/node-static.js:111:13)\n    at finish (/home/medianucenter/node-sonos-http-api-1.0.1/node_modules/node-static/lib/node-static.js:170:14)\n    at /home/medianucenter/node-sonos-http-api-1.0.1/node_modules/node-static/lib/node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:123:15)"}`

I can't just play with this speaker "Chambre", I need to put "http://192.168.1.25:5005/Chambre/playlist/Réveil" in order to play the playlist "Réveil". Is it normal?

Otherwise, all well now if I run the command playing a playlist.

Thank you for your help :-)

**Comment by jishi** [comment]
If the player queue is empty or no other source is selected, you would see this error. But if you have started playlist, then call:

`Chambre/pause`

followed by

`Chambre/play`

I assume it works? Play is basically pushing the play button. Without source, it doesn't know what to do.

**Comment by naixra** [comment]
Ok, I guess it is normal.

Yes, Everything work like a charm now.
