### ISSUE TITLE
new version isnt working for me

### ISSUE THREAD

**Issue by dinkybluebug** [jishi/node-sonos-http-api#342]
I updated for v1.0.1  - it installs ok - but when I use npm start, it comes up with a variety of errors.  Using raspberry pi 3.  Node is version 6.x

output is below, can anyone help?

pi@raspberrypi:~/MagicMirror/modules/node-sonos-http-api-1.0.1 $ npm install --production
sonos-http-api@1.0.1 /home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1
├─┬ anesidora@1.2.1
│ ├─┬ request@2.75.0
│ │ ├── aws-sign2@0.6.0
│ │ ├── aws4@1.5.0
│ │ ├─┬ bl@1.1.2
│ │ │ └─┬ readable-stream@2.0.6
│ │ │   ├── core-util-is@1.0.2
│ │ │   ├── inherits@2.0.3
│ │ │   ├── isarray@1.0.0
│ │ │   ├── process-nextick-args@1.0.7
│ │ │   ├── string_decoder@0.10.31
│ │ │   └── util-deprecate@1.0.2
│ │ ├── caseless@0.11.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.0
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.0.0
│ │ │ └── asynckit@0.4.0
│ │ ├─┬ har-validator@2.0.6
│ │ │ ├─┬ chalk@1.1.3
│ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ ├── strip-ansi@3.0.1
│ │ │ │ └── supports-color@2.0.0
│ │ │ ├─┬ commander@2.9.0
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ ├─┬ is-my-json-valid@2.15.0
│ │ │ │ ├── generate-function@2.0.0
│ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ └── is-property@1.0.2
│ │ │ │ ├── jsonpointer@4.0.0
│ │ │ │ └── xtend@4.0.1
│ │ │ └─┬ pinkie-promise@2.0.1
│ │ │   └── pinkie@2.0.4
│ │ ├─┬ hawk@3.1.3
│ │ │ ├── boom@2.10.1
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.3
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@1.1.1
│ │ │ ├── assert-plus@0.2.0
│ │ │ ├─┬ jsprim@1.3.1
│ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └── verror@1.3.6
│ │ │ └─┬ sshpk@1.10.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0
│ │ │   ├── bcrypt-pbkdf@1.0.0
│ │ │   ├─┬ dashdash@1.14.0
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── ecc-jsbn@0.1.1
│ │ │   ├─┬ getpass@0.1.6
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── jodid25519@1.0.2
│ │ │   ├── jsbn@0.1.0
│ │ │   └── tweetnacl@0.14.3
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.12
│ │ │ └── mime-db@1.24.0
│ │ ├── node-uuid@1.4.7
│ │ ├── oauth-sign@0.8.2
│ │ ├── qs@6.2.1
│ │ ├── stringstream@0.0.5
│ │ ├── tough-cookie@2.3.1
│ │ └── tunnel-agent@0.4.3
│ └── underscore@1.8.3
├── basic-auth@1.0.4
├── fuse.js@2.5.0
├─┬ node-static@0.7.9
│ ├── colors@1.1.2
│ ├── mime@1.3.4
│ └─┬ optimist@0.6.1
│   ├── minimist@0.0.10
│   └── wordwrap@0.0.3
├─┬ request-promise@1.0.2
│ ├── bluebird@2.11.0
│ ├─┬ cls-bluebird@1.1.3
│ │ ├── is-bluebird@1.0.2
│ │ └── shimmer@1.1.0
│ └── lodash@3.10.1
└─┬ sonos-discovery@1.0.1
  ├── html-entities@1.0.10
  └─┬ xml-flow@1.0.1
    └── sax@1.2.1

pi@raspberrypi:~/MagicMirror/modules/node-sonos-http-api-1.0.1 $ npm start

> sonos-http-api@1.0.1 start /home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1
> node server.js

2016-10-14T07:24:45.757Z INFO no settings file found, will only use default settings
2016-10-14T07:24:46.535Z INFO Presets loaded: { example:
   { players:
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'My example favorite' } }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/helpers/try-download-tts.js:11:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/actions/say_v2.js:7:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/actions/say_v2.js:17:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at files.map.filter.forEach (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/helpers/require-dir.js:18:8)
    at Array.forEach (native)
    at module.exports (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/server.js:44:11) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/actions/sayall.js:11:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at files.map.filter.forEach (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/helpers/require-dir.js:18:8)
    at Array.forEach (native)
    at module.exports (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/node-sonos-http-api-1.0.1/server.js:44:11) code: 'MODULE_NOT_FOUND' }
2016-10-14T07:24:46.634Z INFO http server listening on port 5005
^C

**Comment by jishi** [comment]
Looks like it starts but the errors are logged because you have no
settings.json

Did you actually test any http commands?

**Comment by dinkybluebug** [comment]
No I havent, but then I think I am using your module differently.  When I set it up before I didnt make s settings.json file either.

Im using this as part of this module (https://github.com/CFenner/MagicMirror-Sonos-Module) which requires node-sonos-http-api running.  This is part of a bigger programme called magicmirror (https://github.com/MichMich/MagicMirror)

Can you advise - what needs to go in my settings.json file?  Im not actually using any http commands myself.

Many thanks

**Comment by jishi** [comment]
Those errors should merely be warnings, it shouldn't affect the
functionality. If you want to remove the warnings, just do this:

echo {} > settings.json

That would create an empty settings file.

But as I said, it should work anyway, and it looks like it works. If you
want to test it, just visit:

http://ip_of_pi:5005/zones

In a browser. It should render some json describing your sonos topology.

**Comment by dinkybluebug** [comment]
ah ok - that means then the magicmirror module 'https://github.com/CFenner/MagicMirror-Sonos-Module' isnt working-  as its not displaying the current track on the display anymore.  I'll investigate.  Thanks

**Comment by HubertusH** [comment]
I have a problem too - to start the new version:

`> sonos-http-api@1.0.1 start /opt/node-sonos-http-api
> node server.js

2016-10-14T08:54:05.975Z INFO Presets loaded: { example:
   { players:
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'My example favorite' } }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5005
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Object.<anonymous> (/opt/node-sonos-http-api/server.js:113:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

npm ERR! Linux 4.4.22-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@1.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.0.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sonos-http-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/node-sonos-http-api/npm-debug.log
`

but it runs and a test on xxx:5005 works well.
Thanks

**Comment by jishi** [comment]
Looks like you are already running an instance of the http-api. Do you have
an old installation of it?

**Comment by HubertusH** [comment]
yes but i copy the new files over the old once and try to run it.
how can i stop the running process?

**Comment by jishi** [comment]
Easiest would probably be to find the PID and kill it. You must have set up
some sort of autostart for this to happen?

**Comment by jishi** [comment]
Muted settings.json errors and added descriptive error message when http port is already occupied.

**Comment by HubertusH** [comment]
i update your latest version - and i can not kill the node process because it restarts by itself :-(
the "autostart" is installed by "npm start" i think

**Comment by jishi** [comment]
@HubertusH No, npm start doesn't create any autostart setup, that must be your doing. But if you copied the new files over the old one, it should have restarted the new version anyway so might not be a problem? If you continue to have problem, please open a new issue.
