### ISSUE TITLE
player.system.getServiceType is not a function

### ISSUE THREAD

**Issue by maddox** [jishi/node-sonos-http-api#362]
I just pulled master and now I'm getting the following exception after this url call:

    /Kitchen/musicsearch/apple/song/jazz

```
2016-10-29T05:42:22.535Z ERROR 
  TypeError: player.system.getServiceType is not a function
    at /Users/jmaddox/apps/node-sonos-http-api/lib/actions/musicSearch.js:45:48
    at tryCatcher (/Users/jmaddox/apps/node-sonos-http-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/jmaddox/apps/node-sonos-http-api/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/jmaddox/apps/node-sonos-http-api/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/jmaddox/apps/node-sonos-http-api/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/jmaddox/apps/node-sonos-http-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/jmaddox/apps/node-sonos-http-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jmaddox/apps/node-sonos-http-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by jishi** [comment]
Did you run npm install? It requires an updated version of sonos-discovery.

**Comment by maddox** [comment]
Ohhh I missed that. Thanks.

**Comment by maddox** [comment]
Works.
