### ISSUE TITLE
Google Play Music URI error

### ISSUE THREAD

**Issue by Kasbane** [jishi/node-sonos-http-api#369]
Hello jishi!  Thanks for all of your work on this project!  I know it's greatly appreciated by myself and all of the others who use it.  I am having one issue though, as seen in the errors below.  It only seems to crop up when I'm using Google Play Music to cast to Sonos (using Play or any other service directly through the Sonos app works fine) and it's happening with all of my songs.  Any idea what I can do about this?  Thanks in advance for your help!

```
  TypeError: Cannot read property 'startsWith' of undefined
    at Object.tryGetHighResArt (/home/pi/MagicMirror/modules/node_modules/node-sonos-http-api/node_modules/sonos-discovery/lib/musicservices.js:18:10)
    at parseTrackMetadata.then.track (/home/pi/MagicMirror/modules/node_modules/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:255:32)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by jishi** [comment]
This issue is a bit odd. It seem to think that the uri of currentTrack is not defined, which would be super weird even when playing google music.

If you could start the http api with trace logging enabled, I could get a glimpse of the actual data that is sent from the player. Start it with:

`NODE_LOG_LEVEL=trace node server.js`

And run it until it crashes, then give me the output from the last log rows. There should be some XML before the actual crash, that would give me a clue on whats happening.

**Comment by Kasbane** [comment]
The output is below.  Pastebin link is [here](http://pastebin.com/FqQDFFJW) in case that's any easier.  Let me know if you need anything else!

```
2016-11-07T23:40:44.808Z TRACE
 
<Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/">
 
<InstanceID val="0">
 
<TransportState val="PAUSED_PLAYBACK"/>
 
<CurrentPlayMode val="NORMAL"/>
 
<CurrentCrossfadeMode val="0"/>
 
<NumberOfTracks val="1"/>
 
<CurrentTrack val="1"/>
 
<CurrentSection val="0"/>
 
<CurrentTrackURI val="https://mclients.googleapis.com/music/mplay?songid=68d071cd-a0c6-381e-9763-ab64349016e9&amp;dv=36240&amp;pt=e&amp;hl=en_US&amp;tier=fr&amp;slt=1478562013586&amp;sig=YZk8xcBp2x8kE7D_36sHjGU6Z8M"/>
 
<CurrentTrackDuration val="0:03:00"/>
 
<CurrentTrackMetaData val="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt; &lt;item id=&quot;-1&quot; parentID=&quot;-1&quot; restricted=&quot;true&quot;&gt; &lt;res protocolInfo=&quot;http-get:*:audio/mpeg:*&quot; duration=&quot;00:03:00&quot; /&gt; &lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt; &lt;dc:title&gt;Killer Queen&lt;/dc:title&gt; &lt;dc:creator&gt;Queen&lt;/dc:creator&gt; &lt;upnp:album&gt;Greatest Hits I&lt;/upnp:album&gt; &lt;upnp:albumArtURI&gt;http://lh4.ggpht.com/QqvjdkhIGCtQbJn8jnbx1uI45ZRcUgJUzi2SVTDNbOxhIM1VOeAxIVE6r__m9qucQTD7NUAMUvY&lt;/upnp:albumArtURI&gt; &lt;r:http&gt;Authorization: playon=ABHW6GFKRHI5KGWXCW56NTM7FLGY2M4OIW75GY3XHRTZUT7DXGYU3FWKPPLMR6SJYHUCHYEMZ7SAMGTNU2JUMSAT5QXWU4PIPSPFK26WQS3OARG3CSRGZTXAJNDFWBU2Q22KAC3HMJEJB4U3AWEQJLJZM53IKITYFTCVYBNKMUKRJBJWSYWT5QJXTO4MGWO7CWGGPHSHKDWG5E5Y6JIEHOXSPPVSFGDZ5C5VMWMTDOGM5E65QHW2NCVJTUJM64ALPG2CETCAESBGGHMU6ESTPUL3NMI4MM4DOIRJVMYYPPQ534M6R7RB2UDVLBBCFGOXCLCQEC2QHDYHTV2GBA3AHOPZGZ4Z2TZRRYUTOVZDSSPQQJZSD3GX3THRY4N3L2FXZM33EYLZE5CTM5B2VCFDDNBA7BXU6FKCEN6TXJK6XLXX2JU7ME52JSBRWVG3GCAN63EIW2ONJBHW62LWXAOEMAIAZP5UTOLPFL3RKAIR2EFW5XNJDR4CDXMZAH2HMYFPCZQCEWQE4P6GSSRGSLGANYZX7NE6SROFG56JR6YFVAVDH4SMUXN3YL2PVNWKJLPKTGB56C4EIDH5CNOWJVIIHY7XZW7JEM34QEEVYKR73EECR7MOP4FVL5OBLUOWBW2KBMG5E4MYP3RFQBMEARJNNGA25FNLAJS3MO6SYSGUZLI22EBOGDAERKL65VS3XWWGO5NNRF5VY6PYFDJTJM2RDYBWRSYQHGBSQKHRAISMCJ6VIIBXRABG6B36YCZYLSTVK432OOVQHF4VLM75L2U7TVKY4SJXS3HGBWPBBWIB74LRDCEMZVPBZMJMOR3QYL7JL2LRDL33ILOSXF3GO3Z3COHPCKFH2DV4J2PKXOZIZOVUN4KJ2GBXN45TJRKSUXDLTMVB5O5FLDRXCZDER6PXRL72FIVWH2R3JCVRXGTJ6RDYT374BYHN3DXUIK5UIZJ3ERQC3J2A5XHEKHPHN7E5HZVYJLDQ====&lt;/r:http&gt; &lt;/item&gt; &lt;/DIDL-Lite&gt;"/>
 
<r:NextTrackURI val=""/>
 
<r:NextTrackMetaData val=""/>
 
<r:EnqueuedTransportURI val="https://mclients.googleapis.com/music/mplay?songid=68d071cd-a0c6-381e-9763-ab64349016e9&amp;dv=36240&amp;pt=e&amp;hl=en_US&amp;tier=fr&amp;slt=1478562013586&amp;sig=YZk8xcBp2x8kE7D_36sHjGU6Z8M"/>
<r:EnqueuedTransportURIMetaData val="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt; &lt;item id=&quot;-1&quot; parentID=&quot;-1&quot; restricted=&quot;true&quot;&gt; &lt;res protocolInfo=&quot;http-get:*:audio/mpeg:*&quot; duration=&quot;00:03:00&quot; /&gt; &lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt; &lt;dc:title&gt;Killer Queen&lt;/dc:title&gt; &lt;dc:creator&gt;Queen&lt;/dc:creator&gt; &lt;upnp:album&gt;Greatest Hits I&lt;/upnp:album&gt; &lt;upnp:albumArtURI&gt;http://lh4.ggpht.com/QqvjdkhIGCtQbJn8jnbx1uI45ZRcUgJUzi2SVTDNbOxhIM1VOeAxIVE6r__m9qucQTD7NUAMUvY&lt;/upnp:albumArtURI&gt; &lt;r:http&gt;Authorization: playon=ABHW6GFKRHI5KGWXCW56NTM7FLGY2M4OIW75GY3XHRTZUT7DXGYU3FWKPPLMR6SJYHUCHYEMZ7SAMGTNU2JUMSAT5QXWU4PIPSPFK26WQS3OARG3CSRGZTXAJNDFWBU2Q22KAC3HMJEJB4U3AWEQJLJZM53IKITYFTCVYBNKMUKRJBJWSYWT5QJXTO4MGWO7CWGGPHSHKDWG5E5Y6JIEHOXSPPVSFGDZ5C5VMWMTDOGM5E65QHW2NCVJTUJM64ALPG2CETCAESBGGHMU6ESTPUL3NMI4MM4DOIRJVMYYPPQ534M6R7RB2UDVLBBCFGOXCLCQEC2QHDYHTV2GBA3AHOPZGZ4Z2TZRRYUTOVZDSSPQQJZSD3GX3THRY4N3L2FXZM33EYLZE5CTM5B2VCFDDNBA7BXU6FKCEN6TXJK6XLXX2JU7ME52JSBRWVG3GCAN63EIW2ONJBHW62LWXAOEMAIAZP5UTOLPFL3RKAIR2EFW5XNJDR4CDXMZAH2HMYFPCZQCEWQE4P6GSSRGSLGANYZX7NE6SROFG56JR6YFVAVDH4SMUXN3YL2PVNWKJLPKTGB56C4EIDH5CNOWJVIIHY7XZW7JEM34QEEVYKR73EECR7MOP4FVL5OBLUOWBW2KBMG5E4MYP3RFQBMEARJNNGA25FNLAJS3MO6SYSGUZLI22EBOGDAERKL65VS3XWWGO5NNRF5VY6PYFDJTJM2RDYBWRSYQHGBSQKHRAISMCJ6VIIBXRABG6B36YCZYLSTVK432OOVQHF4VLM75L2U7TVKY4SJXS3HGBWPBBWIB74LRDCEMZVPBZMJMOR3QYL7JL2LRDL33ILOSXF3GO3Z3COHPCKFH2DV4J2PKXOZIZOVUN4KJ2GBXN45TJRKSUXDLTMVB5O5FLDRXCZDER6PXRL72FIVWH2R3JCVRXGTJ6RDYT374BYHN3DXUIK5UIZJ3ERQC3J2A5XHEKHPHN7E5HZVYJLDQ====&lt;/r:http&gt; &lt;/item&gt; &lt;/DIDL-Lite&gt;"/>
 
</InstanceID>
 
</Event>
 
 
2016-11-07T23:40:44.875Z ERROR
  TypeError: Cannot read property 'startsWith' of undefined
    at Object.tryGetHighResArt (/home/pi/MagicMirror/modules/node_modules/node-sonos-http-api/node_modules/sonos-discovery/lib/musicservices.js:18:10)
    at parseTrackMetadata.then.track (/home/pi/MagicMirror/modules/node_modules/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:255:32)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by jishi** [comment]
Thank you, I see the problem now. I'll try to look at it tonight.

**Comment by jishi** [comment]
I think this should be fixed now, remember to update your dependencies since this relies on an updated sonos-discovery package.
