### ISSUE TITLE
HTTPS problem?

### ISSUE THREAD

**Issue by lisa262** [jishi/node-sonos-http-api#370]
Jishi, thanks for all of your hard work on this project. I'm at wit's end trying to figure out why I'm having issues with my HTTPS settings. I have my key/crt files correctly placed in the settings.json file:

```
  "https": {
        "key": "/home/pi/node-sonos-http-api/server.key",
        "cert": "/home/pi/node-sonos-http-api/server.crt"
      },
```

But I'm still getting this error when I run the server:

```
/home/pi/node-sonos-http-api/server.js:63
    options.key = fs.readFileSync(settings.https.key);
                  ^

ReferenceError: fs is not defined
    at Object.<anonymous> (/home/pi/node-sonos-http-api/server.js:63:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

```
Thanks in advance!

**Comment by jishi** [comment]
That's an error on my part. Seems like a did a tad too aggressive cleanup. I have fixed this issue in the latest master.
