### ISSUE TITLE
Presets 

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#373]
Is there or there be a way to add a command in preset for the controller to be set to line in input

Many thanks in advance 

Regards

Robert

**Comment by jishi** [comment]
Yes, this is possible. If you specify no favorite nor playlist, and instead:

`"uri": "x-rincon-stream:[UUID of line-in player]"`

It would switch to the line in for that specified player. You can find the UUID of said player from the `/state`

This is for a regular line-in, for a PLAYBAR line-in there is another schema:

`x-sonos-htastream:RINCON_XXXXXXXXXXXX01400:spdif`

**Comment by robertw** [comment]
{
  "players": [
    {
      "roomName": "Bathroom",
      "volume": 20
    },
    {
      "roomName": "Family Room",
      "volume": 30
    },
    {
      "roomName": "Office",
      "volume": 20
    },
    {
      "roomName": "Master Bedroom",
      "volume": 20
    },
    {
      "roomName": "Living Room",
      "volume": 30
    }
  ],
  "playMode": {
    "crossfade": false
  },
  "pauseOthers": false,
  "uri":"x-rincon-stream:RINCON_000E5822185201400 type:line_in"
}

what am i doing wrong ?

error:{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/home/pi/sonosapi/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n    at Player.setAVTransport (/home/pi/sonosapi/node_modules/sonos-discovery/lib/models/Player.js:652:15)\n    at promise.then (/home/pi/sonosapi/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:121:46)\n    at process._tickCallback (internal/process/next_tick.js:103:7)"}

**Comment by jishi** [comment]
Your preset uri is wrong...

replace:
`"uri":"x-rincon-stream:RINCON_000E5822185201400 type:line_in"`
with
`"uri":"x-rincon-stream:RINCON_000E5822185201400"`

**Comment by robertw** [comment]
Ok super but now i am trying to get it to play....
{
  "players": [
    {
      "roomName": "Bathroom",
      "volume": 20
    },
    {
      "roomName": "Family Room",
      "volume": 30
    },
    {
      "roomName": "Office",
      "volume": 20
    },
    {
      "roomName": "Master Bedroom",
      "volume": 20
    },
    {
      "roomName": "Living Room",
      "volume": 30
    }
  ],
  "playMode": {
    "crossfade": false,
	"state": "PLAYING"
  },
  "pauseOthers": false,
  "uri":"x-rincon-stream:RINCON_000E5822185201400"
}

err:
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/home/pi/sonosapi/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n    at Player.setAVTransport (/home/pi/sonosapi/node_modules/sonos-discovery/lib/models/Player.js:652:15)\n    at promise.then (/home/pi/sonosapi/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:58:40)\n    at process._tickCallback (internal/process/next_tick.js:103:7)"}

**Comment by jishi** [comment]
It seems to fail when trying to group one of the players to Bathroom, not sure why. Could you try with only Bathroom to start with, and add them one by one to the preset and see which one breaks? Or run it with
`NODE_LOG_LEVEL=debug npm start` 

to get the debug output as well. It would log every step of the preset and it would be evident at which step it fails.

**Comment by robertw** [comment]
i changed the controller to the office

{
  "players": [
    {
      "roomName": "Office",
      "volume": 20
    },
    {
      "roomName": "Family Room",
      "volume": 30
    },
    {
      "roomName": "Bathroom",
      "volume": 20
    },
    {
      "roomName": "Master Bedroom",
      "volume": 20
    },
    {
      "roomName": "Living Room",
      "volume": 30
    }
  ],
  "playMode": {
    "crossfade": false,
	"state": "PLAYING"
  },
  "pauseOthers": false,
  "uri":"x-rincon-stream:RINCON_000E5822185201400"
}



root@raspberrypi:/home/pi/sonosapi# NODE_LOG_LEVEL=debug npm start

> sonos-http-api@1.1.7 start /home/pi/sonosapi
> node server.js

2016-11-12T18:10:58.399Z INFO no settings file found, will only use default settings
2016-11-12T18:10:58.414Z DEBUG
  { port: 5005,
  securePort: 5006,
  cacheDir: '/home/pi/sonosapi/cache',
  webroot: '/home/pi/sonosapi/static',
  presetDir: '/home/pi/sonosapi/presets',
  announceVolume: 40 }
2016-11-12T18:11:00.083Z DEBUG no presets.json file exists, skipping
2016-11-12T18:11:00.107Z INFO Presets loaded: { example:
   { players:
      [ { roomName: 'Office', volume: 20 },
        { roomName: 'Family Room', volume: 30 },
        { roomName: 'Bathroom', volume: 20 },
        { roomName: 'Master Bedroom', volume: 20 },
        { roomName: 'Living Room', volume: 30 } ],
     playMode: { crossfade: false, state: 'PLAYING' },
     pauseOthers: false,
     uri: 'x-rincon-stream:RINCON_000E5822185201400' },
  robert:
   { players: [ { roomName: 'Living Room', volume: 55 } ],
     playMode: { crossfade: false },
     pauseOthers: false,
     favorite: 'Carlos Radio' } }
2016-11-12T18:11:00.266Z INFO http server listening on port 5005
(node:801) Warning: Possible EventEmitter memory leak detected. 11 group-mute listeners added. Use emitter.setMaxListeners() to increase limit
(node:801) Warning: Possible EventEmitter memory leak detected. 11 last-change listeners added. Use emitter.setMaxListeners() to increase limit
2016-11-12T18:11:03.592Z DEBUG No such service x-rincon-stream:RINCON_000E5822185201400
2016-11-12T18:11:03.603Z DEBUG No such service x-sonosprog-http:A0DvPDnowsK5hFV5Z_86cRiZdLkDoFwBGcExbzuWg466PHsE1XlvCQ.mp3?sid=151&flags=32&sn=8
2016-11-12T18:11:03.605Z DEBUG No such service x-sonos-http:A0DvPDnowsI6aC6Zizo_s57nT5uB5A8bTXVfdUUNqlMR8A6dw3R8xQ.mp3?sid=151&flags=32&sn=8
2016-11-12T18:11:03.711Z DEBUG No such service x-sonos-http:A0DvPDnowsLHg6njGeagew_V43QolyvlLZ82L-Q3h9J56G1qOZd1zw.mp3?sid=151&flags=32&sn=8
2016-11-12T18:12:15.906Z DEBUG coordinator is Office
2016-11-12T18:12:15.910Z DEBUG adding Family Room to coordinator Office
2016-11-12T18:12:15.912Z DEBUG adding Bathroom to coordinator Office
2016-11-12T18:12:15.912Z DEBUG adding Master Bedroom to coordinator Office
2016-11-12T18:12:15.913Z DEBUG adding Living Room to coordinator Office
2016-11-12T18:12:16.525Z DEBUG setting volume 20 on Office
2016-11-12T18:12:16.555Z DEBUG setting volume 30 on Family Room
2016-11-12T18:12:16.574Z DEBUG setting volume 20 on Bathroom
2016-11-12T18:12:16.590Z DEBUG setting volume 20 on Master Bedroom
2016-11-12T18:12:16.608Z DEBUG setting volume 30 on Living Room
2016-11-12T18:12:16.736Z ERROR
  Error
    at Object.invoke (/home/pi/sonosapi/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)
    at promise.then (/home/pi/sonosapi/node_modules/sonos-discovery/lib/models/Player.js:607:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-11-12T18:12:19.901Z DEBUG No such service x-rincon-stream:RINCON_000E5822185201400

**Comment by jishi** [comment]
Okay, looks like the crossfade settings gives you an error, I don't seem to ignore that. Remove playMode altogether from the preset since it doesn't make sense for a line-in.

Also, `state` shouldn't be under playMode, ot should be directly in the preset.

**Comment by robertw** [comment]
Many thanks that did work just fine .......
