### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by ppitkin** [jishi/node-sonos-http-api#383]
I've obviously broken something....

any ideas?

[00:12:14.232] [ERROR] resubscribing to sid null failed { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[00:12:33.176] [ERROR] resubscribing to sid null failed { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[00:12:49.049] [ERROR] resubscribing to sid null failed { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[00:14:15.191] [ERROR] resubscribing to sid null failed { Error: connect ETIMEDOUT 192.168.0.108:1400
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.0.108',
  port: 1400 }
[00:15:48.760] [ERROR] resubscribing to sid null failed { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[00:16:07.704] [ERROR] resubscribing to sid null failed { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[00:16:22.297] [ERROR] resubscribing to sid null failed { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[00:17:49.592] [ERROR] resubscribing to sid null failed { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[00:19:22.009] [ERROR] resubscribing to sid null failed { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)

**Comment by jishi** [comment]
Is this constant? Sounds like your Sonos players have changed IPs, or you have blocked outgoing traffic from the device you are running this on. 

I am currently fixing rediscovery if your system changes IPs or when the player you are subscribing for topology updates goes down. I have fixed it, I just haven't updated the http-api with that codebase yet (it need some small changes).

**Comment by ppitkin** [comment]
It shouldn't be due to an IP change as I have the IP's fixed in the DHCP server and they should anyway only renew once a week. I wasn't seeing the errors ealier in the week but it started sometime yesterday. I have restarted the api several times but the error message still comes up.
I do occationally get that the Sonos players lock up (especially on the Play:1's). Usually just trying to play something from the windows controller app free's things up.
I am running a Beta version of the software as I had to enter the Beta program in order to get the Plex functionality.
The messages don't seem to be causing an issue as the api is still working. I was just not sure why they are getting produced.

**Comment by jishi** [comment]
They are related to subscription of events from the players, and it will try to resubscribe indefinitely. I usually see these on my laptop when I have it running while it goes into sleep mode. When it wakes up, it will try to resubscribe directly but the network hasn't woken up yet. 

If it works, I wouldn't worry about it. There is also some remnant logging that shouldn't be there which I'm about to remove. What device are you running this on? And what network connectivity does it have?

**Comment by ppitkin** [comment]
running on a Debian Cinnamon VM located on my NAS (QNAP1080).
Network is physical to Router and 2 Sonos Bridges and Wireles to the Sonos Players (Sonos network not my normal Wifi). IP address registerd in the DHCP on the router (Fritzbox).

I'll fire up the Pi3 instance and see if it does the same.

**Comment by ppitkin** [comment]
OK just confirmed that it does it on the RasPi as well.

**Comment by ppitkin** [comment]
starts outputting the messages about 3-4 minutes after restarting the app.

**Comment by jishi** [comment]
Is 192.168.0.108 one of your Sonos players?

**Comment by ppitkin** [comment]
Seems like the firmware locked up on the player. Restarting it got it working again.
