### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by ggravlingen** [jishi/node-sonos-http-api#399]
Getting this error when trying to start the server

```
pi@raspberrypi:/opt/node-sonos-http-api$ sudo node server.js 
2016-12-05T21:38:21.801Z INFO no settings file found, will only use default settings
/opt/node-sonos-http-api/lib/actions/playmode.js:2
  let mode = values[0];
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /opt/node-sonos-http-api/lib/helpers/require-dir.js:18:8
    at Array.forEach (native)
    at module.exports.files.map.filter (/opt/node-sonos-http-api/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/opt/node-sonos-http-api/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/opt/node-sonos-http-api/server.js:14:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

```

**Comment by jishi** [comment]
You are running node 4? Forgot that I need to specify strict mode. Will fix

**Comment by ggravlingen** [comment]
pi@raspberrypi:/opt/node-sonos-http-api$ node --version
v4.6.2

**Comment by jishi** [comment]
All fixed now. Found some other files that suffered from the same issue which I corrected.

**Comment by ggravlingen** [comment]
Works now, thanks!
