### ISSUE TITLE
Error when running??

### ISSUE THREAD

**Issue by AdamCapes** [jishi/node-sonos-http-api#442]
Hi Jishi.  Im getting this error below.  Have i missed something?  I do have a settings.js file there so dont know why that INFO is appearing.  I am running this from a VirtualBox VM and Ubuntu if that could be causing a problem?

2017-01-21T00:53:14.762Z INFO no settings file found, will only use default settings
2017-01-21T00:53:15.187Z INFO Presets loaded: { example: 
   { players: [ { roomName: 'Kitchen', volume: 10 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false } }
2017-01-21T00:53:15.445Z INFO http server listening on port 5005
2017-01-21T00:53:17.208Z WARN resubscribing to sid undefined failed
  Error: connect ECONNREFUSED 10.0.2.2:1400
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by jishi** [comment]
I assume that 10.0.2.2 is not the IP of any Sonos player, it looks like a virtualbox NAT network. Change your VM to use "Bridged adapter" mode for the network interface and see if that helps. That would expose your VM directly on your local network.

**Comment by AdamCapes** [comment]
You legend, thats the ticket!  Cheers.
