### ISSUE TITLE
Locking volumes crashes server

### ISSUE THREAD

**Issue by pheintzelman** [jishi/node-sonos-http-api#446]
This isn't a feature I need but I did run into this.

Stack Trace:
2017-01-23T07:32:24.432Z INFO http server listening on port 5005
locking volumes
C:\node-sonos-http-api\lib\actions\lockvolumes.js:11
    lockVolumes[i] = player.state.volume;
                                 ^

TypeError: Cannot read property 'volume' of undefined
    at Object.lockvolumes (C:\node-sonos-http-api\lib\actions\lockvolumes.js:11:34)
    at handleAction (C:\node-sonos-http-api\lib\sonos-http-api.js:110:35)
    at HttpAPI.requestHandler (C:\node-sonos-http-api\lib\sonos-http-api.js:87:5)
    at C:\node-sonos-http-api\server.js:50:13
    at Server.finish (C:\node-sonos-http-api\node_modules\node-static\lib\node-static.js:111:13)
    at finish (C:\node-sonos-http-api\node_modules\node-static\lib\node-static.js:170:14)
    at C:\node-sonos-http-api\node_modules\node-static\lib\node-static.js:144:17
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by jishi** [comment]
Thanks for reporting. We have a discussion about changing this functionality to be a maxvolume feature instead, it would make more sense to me. https://github.com/jishi/node-sonos-http-api/issues/409

**Comment by jishi** [comment]
Fixed in 1.2.7.
