### ISSUE TITLE
SyntaxError: Use of const in strict mode when starting npm (raspberrian OS, pi 3 model B (arm, 32 bit)

### ISSUE THREAD

**Issue by jzajac2** [jishi/node-sonos-http-api#464]
following steps on a raspberry pi 3 model B (arm, 32 bit), when I `npm install` I get the following error:

```
pi@raspberrypi:~/code/node-sonos-http-api-master $ npm start

> sonos-http-api@1.2.7 start /home/pi/code/node-sonos-http-api-master
> node server.js


/home/pi/code/node-sonos-http-api-master/server.js:2
const http = require('http');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! sonos-http-api@1.2.7 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.2.7 start script.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.38-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/code/node-sonos-http-api-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/code/node-sonos-http-api-master/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jzajac2** [comment]
pi@raspberrypi:~/code/node-sonos-http-api-master $ node --version
v0.10.29
pi@raspberrypi:~/code/node-sonos-http-api-master $ npm --version
1.4.21

**Comment by jishi** [comment]
You need to use node 4.0 or higher, you are using node 0.10

Search amongst the closed issues, I have several explanations of options.

Best is to download the armv7 version from nodejs.org
