### ISSUE TITLE
Spotify search appears to be broken

### ISSUE THREAD

**Issue by evansgo** [jishi/node-sonos-http-api#481]
I use http://localhost:5005/study/spotify/now/spotify:track:4LI1ykYGFCcXPWkrpcU7hn and the song plays fine.

http://localhost:5005/study/musicsearch/library/song/artist:abba also works fine

But if I use http://localhost:5005/study/musicsearch/spotify/song/artist:abba, nothing happens.

Looking in the console I get this:-
2017-03-25T07:44:00.423Z ERROR
StatusCodeError: 400 - [object Object]
at new StatusCodeError (/Users/g/node-sonos-http-api/node_modules/request-promise/lib/errors.js:26:15)
at Request.RP$callback [as _callback] (/Users/g/node-sonos-http-api/node_modules/request-promise/lib/rp.js:68:32)
at Request.self.callback (/Users/g/node-sonos-http-api/node_modules/request/request.js:188:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:194:7)
at Request. (/Users/g/node-sonos-http-api/node_modules/request/request.js:1171:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:191:7)
at IncomingMessage. (/Users/g/node-sonos-http-api/node_modules/request/request.js:1091:12)
at Object.onceWrapper (events.js:293:19)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:188:7)
at endReadableNT (_stream_readable.js:975:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)

I have tried the release version of Node and the 'Latest' neither make a difference. Can anyone suggest a fix?

Since I wrote this I signed up to Apple Music to see if it would work and that also seems to work fine, so this problem is Spotify specific...

Thanks....

**Comment by jishi** [comment]
Is this still a problem?
