### ISSUE TITLE
Strange New Error

### ISSUE THREAD

**Issue by jplourde5** [jishi/node-sonos-http-api#488]
Over the weekend commands stopped working.  Nothing had changed that I know of unless Sonos performed an automatic update.  Downloaded and installed latest nsha updates.  The error I'm getting is:

http://localhost:5005/Living%20Room/musicsearch/apple/song/alison
2017-04-18T08:34:37.495Z ERROR 
 [object Object]
    at Object.invoke (/home/pi/NodeApps/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)
    at Player.play (/home/pi/NodeApps/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:442:15)
    at player.coordinator.getQueue.then.then.then.then.then (/home/pi/NodeApps/node-sonos-http-api-master/lib/actions/musicSearch.js:273:48)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

Any clues before I dig in deep?

**Comment by jishi** [comment]
No, not that I can think of. Seems like it's not logging the relevant
information, so it's not very useful. I'm away on a vacation right now, so
can't really look into it atm.

**Comment by jplourde5** [comment]
Enjoy your vacation.  Appears that the problem is with any low level command like play, pause, and skip.  I'm getting the problem on both my RP3 and Mac.  I'm using the latest release of everything and the problem started with an older version.  I'm going to try restarting the Sonos devices.

**Comment by jplourde5** [comment]
Restarting a couple of the SONOS devices including the one connected to the router seems to have things going again.
