### ISSUE TITLE
new install with raspberry os and node v7.9.0

### ISSUE THREAD

**Issue by Slepperpon** [jishi/node-sonos-http-api#489]
pi@raspberrypi:~ $ npm install --production
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

**Comment by jishi** [comment]
Have you actually downloaded this repository (either as a zip, or a git clone)? You seem to be standing on your home folder, not the actual folder of the source. There should be a package.json in that folder, that is why npm is complaining.

**Comment by Slepperpon** [comment]
This is what i get know seems that most of it works but getting errors 
Thank you for all your help and sorry if i am just missing something simple. 


pi@raspberrypi:~/node_modules/sonos-http-api $ npm start

> sonos-http-api@1.4.1 start /home/pi/node_modules/sonos-http-api
> node server.js

2017-04-21T14:43:57.529Z INFO Could not find file /home/pi/node_modules/sonos-http-api/settings.json
2017-04-21T14:43:59.840Z WARN Could not read file /home/pi/node_modules/sonos-http-api/presets/presets.json, ignoring.
  SyntaxError: Expected '}' instead of '"' at line 13 column 3 of the JSON5 data. Still to read: "\"sleep\": 600\n}"
    at error (/home/pi/node_modules/sonos-http-api/node_modules/json5/lib/json5.js:56:25)
    at next (/home/pi/node_modules/sonos-http-api/node_modules/json5/lib/json5.js:72:17)
    at object (/home/pi/node_modules/sonos-http-api/node_modules/json5/lib/json5.js:464:25)
    at value (/home/pi/node_modules/sonos-http-api/node_modules/json5/lib/json5.js:482:20)
    at Object.parse (/home/pi/node_modules/sonos-http-api/node_modules/json5/lib/json5.js:508:18)
    at tryLoadJson (/home/pi/node_modules/sonos-http-api/lib/helpers/try-load-json.js:8:33)
    at files.map.filter.forEach (/home/pi/node_modules/sonos-http-api/lib/actions/preset.js:51:22)
    at Array.forEach (native)
    at readPresetsFromDir (/home/pi/node_modules/sonos-http-api/lib/actions/preset.js:49:6)
    at initPresets (/home/pi/node_modules/sonos-http-api/lib/actions/preset.js:85:3)
    at module.exports (/home/pi/node_modules/sonos-http-api/lib/actions/preset.js:92:3)
    at HttpAPI.requireDir (/home/pi/node_modules/sonos-http-api/lib/sonos-http-api.js:46:5)
    at files.map.filter.forEach (/home/pi/node_modules/sonos-http-api/lib/helpers/require-dir.js:18:5)
    at Array.forEach (native)
    at module.exports (/home/pi/node_modules/sonos-http-api/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/pi/node_modules/sonos-http-api/lib/sonos-http-api.js:45:3)
2017-04-21T14:43:59.848Z WARN could not parse preset file presets.json, please make sure syntax conforms with JSON5.
2017-04-21T14:43:59.860Z INFO Presets loaded: {}
2017-04-21T14:44:01.700Z INFO http server listening on port 5005

**Comment by jishi** [comment]
You have an error in your presets.json file. Since you've put it in the
presets folder, you should only have one file per preset, and name it with
the name the name of the preset, like chill.js, or similar.

Please read the documentation again and look at the examples again.

**Comment by Slepperpon** [comment]
All working now thank you.
