### ISSUE TITLE
Latest update - crash Unexpected token {

### ISSUE THREAD

**Issue by PointPubMedia** [jishi/node-sonos-http-api#519]
Got this when starting the latest update!

/opt/node-sonos-http-api/lib/music_services/spotifyDef.js:58
const mapResponse = ({ access_token, token_type, expires_in }) => ({
                     ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/node-sonos-http-api/lib/actions/musicSearch.js:7:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /opt/node-sonos-http-api/lib/helpers/require-dir.js:18:8
    at Array.forEach (native)

**Comment by PointPubMedia** [comment]
/opt/node-sonos-http-api/lib/music_services/spotifyDef.js:58
const mapResponse = ({ access_token, token_type, expires_in }) => ({
                     ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/node-sonos-http-api/lib/actions/musicSearch.js:7:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /opt/node-sonos-http-api/lib/helpers/require-dir.js:18:8
    at Array.forEach (native)

**Comment by PointPubMedia** [comment]
Upgrade node from v4 to v6 and works perfectly!

**Comment by jishi** [comment]
Yeah, that destructure statement won't fly in node 4. I wanted to target node 4 because it can be tricky to find support for newer version on some platforms, but it would be convenient to stop support node 4. Maybe the node version parity is much better now anyways.
