### ISSUE TITLE
401 error when attempting to search for song from Spotify

### ISSUE THREAD

**Issue by mkayen** [jishi/node-sonos-http-api#521]
Getting 401 unauthorized error when attempting musicsearch within sonos. I am able to select and play songs directly from sonos client.

Here's the error. Thoughts?:

2017-06-16T16:18:57.274Z ERROR 
  StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/Users/Max/maxdev/googleHomeSonos/node-sonos-http-api/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/Users/Max/maxdev/googleHomeSonos/node-sonos-http-api/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/Users/Max/maxdev/googleHomeSonos/node-sonos-http-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Max/maxdev/googleHomeSonos/node-sonos-http-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Max/maxdev/googleHomeSonos/node-sonos-http-api/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by mkayen** [comment]
also localhost:port/play & localhost:port/pause works. localhost:port/room/musicsearch/spotify/song/artistName results in the 401 above.

**Comment by jplourde5** [comment]
Spotify now requires authentication for its search API. You will need to install the latest version of this solution and follow the readme instructions.
