### ISSUE TITLE
node-sonos-http-api on a Raspberry Pi

### ISSUE THREAD

**Issue by siwica** [jishi/node-sonos-http-api#525]
I am trying to start the node-sonos-http-api on a Raspberry Pi with `node 4.0.0` and `npm 2.14.2` installed. However I get the following error after running `npm start`. Any ideas how to fix this?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart sonos-http-api@1.4.1
6 info start sonos-http-api@1.4.1
7 verbose unsafe-perm in lifecycle true
8 info sonos-http-api@1.4.1 Failed to exec start script
9 verbose stack Error: sonos-http-api@1.4.1 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid sonos-http-api@1.4.1
11 verbose cwd /home/pi/.conf/node-sonos-http-api
12 error Linux 4.1.7-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error sonos-http-api@1.4.1 start: `node server.js`
17 error Exit status 1
18 error Failed at the sonos-http-api@1.4.1 start script 'node server.js'.
18 error This is most likely a problem with the sonos-http-api package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls sonos-http-api
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by jishi** [comment]
could you try starting it with `node server.js`and check the output? Also, see if there is a difference with a newer version of node 4, like 4.4+ or 4.7+.

**Comment by siwica** [comment]
I am getting the following error with 4, 4.4 and 4.7:

2017-06-22T18:11:05.452Z INFO Could not find file /home/pi/.conf/node-sonos-http-api/settings.json
module.js:327
    throw err;
    ^

```
Error: Cannot find module '../internal/assignWith'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/.conf/node-sonos-http-api/node_modules/request-promise/node_modules/lodash/object/assign.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/.conf/node-sonos-http-api/node_modules/request-promise/lib/rp.js:4:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

```

**Comment by jishi** [comment]
Weird error. Try creating a file called settings.json at that location with
the only content being:

`{}`

And see if that helps.

**Comment by siwica** [comment]
What exact path do you mean? `../internal/assignWith` relative to `node_modules/request-promise/node_modules/lodash/object/assign.js`?

**Comment by jishi** [comment]
No, /home/pi/.conf/node-sonos-http-api/settings.json

**Comment by jishi** [comment]
But it looks more like there is some problem with the installed
dependencies. Remove the node_modules folder and run npm install again, see
if that helps.

**Comment by siwica** [comment]
Deleting the node_modules directory and running npm install again solved the problem. I did run it with different nodejs versions before and thought subsequent runs would just overwrite the previous node_modules directory which apparently was not the case. 

Thank you for the help! Great project!
