### ISSUE TITLE
"status":"error" Invalid URI \"undefined[Playlist]\  with Deezer

### ISSUE THREAD

**Issue by Kernum** [jishi/node-sonos-http-api#543]
Hello,
i'm using your great API to manage my Sonos. All is working well.

Just i have an error when i try to play one of my Deezer' Playlist.
I use this command "/my_room/musicsearch/deezer/playlist/my_playlist" as you describe in your doc.
The error message is : 
<quote>
{"status":"error","error":"Error: Invalid URI \"undefinedmy_playlist\"","stack":"RequestError: Error: Invalid URI \"undefinedmy_playlist\"\n    at new RequestError (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/request-promise/lib/errors.js:11:15)\n    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/request-promise/lib/rp.js:60:32)\n    at self.callback (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/request/request.js:188:22)\n    at emitOne (events.js:77:13)\n    at Request.emit (events.js:169:7)\n    at Request.init (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/request/request.js:276:17)\n    at Request.RP$initInterceptor [as init] (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/request-promise/lib/rp.js:123:25)\n    at new Request (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/request/request.js:130:8)\n    at request (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/request/index.js:54:10)\n    at doSearch (/usr/local/lib/node_modules/node-sonos-http-api-master/lib/actions/musicSearch.js:124:12)\n    at /usr/local/lib/node_modules/node-sonos-http-api-master/lib/actions/musicSearch.js:204:14\n    at tryCatcher (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/bluebird/js/main/promise.js:584:18)\n    at Async._drainQueue (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/usr/local/lib/node_modules/node-sonos-http-api-master/node_modules/bluebird/js/main/async.js:133:10)"}
</quote>

This playlist is working well when i use Sonos-controller to play it and i respect majuscules when i write the name.

I don't know what to do to make it working.
Thanks for help and sorry for my english (i'm french :-p)

Kernum

**Comment by jishi** [comment]
Maybe @jplourde5 find this familiar?

**Comment by Kernum** [comment]
Thanks for answer.
I watched it's not similar :s 
I'm using your scripts with Eedomus Box (domotic box) and i sent a message to the support to know if they integrated the script correctly. 
Maybe i have this error because the scripts on their box is not correct.
I will wait their answer and i will contact you back if there is no solution.
Thanks again for you help :)
Kernum
