### ISSUE TITLE
Spotify Issue

### ISSUE THREAD

**Issue by bosyd** [jishi/node-sonos-http-api#547]
Can anyone assist me.  I am running the following command:

http://localhost:5005/Dining%20Room/musicsearch/spotify/song/joe

And I am getting the following in the command window:

2017-08-06T07:55:01.641Z ERROR
  StatusCodeError: 401 - [object Object]
    at new StatusCodeError (C:\Users\bowen\node_modules\request-promise\lib\errors.js:26:15)
    at Request.RP$callback [as _callback] (C:\Users\bowen\node_modules\request-promise\lib\rp.js:68:32)
    at Request.self.callback (C:\Users\bowen\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\bowen\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\bowen\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

When I use command to perform a musicsearch from my library, everything works fine (http://localhost:5005/Dining%20Room/musicsearch/library/song/joe)

I followed the instructions in the thread and created a Spotify application and enetered in the keys within the settings.json file.

Any help would be appreciated.

**Comment by jishi** [comment]
Statuscode 401 means trouble with the authentication, so make sure they are
entered correctly in the settings file.

**Comment by bosyd** [comment]
I am new to this so I am sure I am doing something incorrect.  In your settings.json, I only saw the clientID and ClientSecret under the Spotify section.  I did see the 

	  "auth": {
	    "username": "admin",
	    "password": "password"

section, but I did not think that was specific to Spotify.

**Comment by jishi** [comment]
Do note that the properties in settings.json is case sensitive. Double
check against the readme how you spell clientid and clientsecret

**Comment by bosyd** [comment]
Thanks mate.  I am not a programmer, but want to get Google Home integration with my Sonos system.

**Comment by bosyd** [comment]
The spelling and case are as per the readme file.  I just copied the section and created the settings.json

**Comment by jishi** [comment]
Are you running the latest version? This is a late addition, and the authentication was added at that point, even though the music search worked previously.

**Comment by bosyd** [comment]
I am using version 1.2.6.  I will read all the associated readme files as I do not want to take up all of your time. Hopefully I can get this all sorted.  All of the files are executing without an issue with the exception of Spotify

**Comment by jishi** [comment]
Yeah, I think you need to run version 1.4 at least, or something. Don't remember exactly. Are you using the raspberry pi-image? I should probably roll out a new version for that one.

**Comment by bosyd** [comment]
No I am running it on Windows. Where do I get the 1.4 version? I did not see it in the releases.

Sent from my iPad

On 6 Aug 2017, at 23:45, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, I think you need to run version 1.4 at least, or something. Don't remember exactly. Are you using the raspberry pi-image? I should probably roll out a new version for that one.

**Comment by bosyd** [comment]
No worries.  I see you that you recently uploaded it.  I will try this now.

**Comment by jishi** [comment]
I just made a release. Usually people just run the latest master branch,
but I see why getting releases seems more logical.

**Comment by bosyd** [comment]
I have updated to the latest release.  However, I am now getting an error with my settings file.  The error is:

2017-08-06T14:33:27.362Z WARN Could not read file C:\Users\bowen\node-sonos-http-api-1.4.3\settings.json, ignoring.
  SyntaxError: Expected '}' instead of '"' at line 10 column 6 of the JSON5 data. Still to read: "\"pfx\": \"/path/to/pfx"
    at error (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\json5\lib\json5.js:56:25)
    at next (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\json5\lib\json5.js:72:17)
    at object (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\json5\lib\json5.js:464:25)
    at value (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\json5\lib\json5.js:482:20)
    at object (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\json5\lib\json5.js:459:35)
    at value (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\json5\lib\json5.js:482:20)
    at Object.parse (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\json5\lib\json5.js:508:18)
    at tryLoadJson (C:\Users\bowen\node-sonos-http-api-1.4.3\lib\helpers\try-load-json.js:8:33)
    at Object.<anonymous> (C:\Users\bowen\node-sonos-http-api-1.4.3\settings.js:28:22)
    at Module._compile (module.js:570:32)

Here is my settings.json file (I have taken out mu unique ids and credentials:

{
	  "voicerss": "voicerss",
	  "port": 5005,
	  "securePort": 5006,
	  "https": {
	    "key": "/path/to/key.pem",
	    "cert" : "/path/to/cert.pem"

	  // for pfx (alternative configuration)
	    "pfx": "/path/to/pfx.pfx",
	    "passphrase": "your-passphrase-if-applicable"
	  },
	  "auth": {
	    "username": "admin",
	    "password": "password"
	  },
	  "announceVolume": 40,
	  "pandora": {
	    "username": "username",
	    "password": "password"
	  },
	  "spotify": {
	    "clientId": "clientID",
	    "clientSecret": "clientSecret"
	  },
	  "library": {
	    "randomQueueLimit": 50
	  }
	}

**Comment by bosyd** [comment]
Also, i am getting this error now for the Spotify musicsearch:

Error: You are missing spotify clientId and secret in settings.json! Please read the README for instructions on how to generate and add them
    at getHeaders (C:\Users\bowen\node-sonos-http-api-1.4.3\lib\music_services\spotifyDef.js:66:11)
    at getOptions (C:\Users\bowen\node-sonos-http-api-1.4.3\lib\music_services\spotifyDef.js:78:14)
    at auth (C:\Users\bowen\node-sonos-http-api-1.4.3\lib\music_services\spotifyDef.js:88:19)
    at Promise (C:\Users\bowen\node-sonos-http-api-1.4.3\lib\music_services\spotifyDef.js:110:5)
    at authenticateService (C:\Users\bowen\node-sonos-http-api-1.4.3\lib\music_services\spotifyDef.js:109:10)
    at request.then (C:\Users\bowen\node-sonos-http-api-1.4.3\lib\actions\musicSearch.js:126:21)
    at tryCatcher (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

The settings.json file is located in the root program folder, so I am not sure why it is saying I am missing the clientId and secret as they are in my settings.json file.

**Comment by jishi** [comment]
The settings file is invalid, because it contains the comment about the pfx
support. That is not valid json. I suggest you clean out anything you don't
want in the file, but most importantly the // comment row.

**Comment by bosyd** [comment]
I have d ome what you said and took out the secure port related information.  Now the program starts up, but when I try to use the command: http://localhost:5005/Dining%20Room/musicsearch/spotify/song/joe

I get:

ERROR
  RequestError: Error: getaddrinfo ENOTFOUND ipinfo.io ipinfo.io:80
    at new RequestError (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\bowen\node-sonos-http-api-1.4.3\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by jishi** [comment]
Does http://ipinfo.io work from that machine? Not sure why it would try and
hit that, but something is obviously wrong with DNS resolution of that
host.

**Comment by bosyd** [comment]
Yes, I can get to http://ipinfo.io without an issue

IP Address Details - ipinfo.io<http://ipinfo.io/>
ipinfo.io
IP Geolocation, Hostname, Network Owner and More. Comprehensive IP Address Information and REST API from ipinfo.io




Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by bosyd** [comment]
Hey mate.  I tried out the functionality again this morning and now the musicsearchcommand for Spotify works.  I still get an error:

WARN resubscribing to sid uuid:RINCON_000E5863DB0001400_sub0000004765 failed
  Error: connect ETIMEDOUT 192.168.2.12:1400
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
spotify 78e161924ebb42d4b2a4bde8f9cf5507 8dc73478654b4bc2bd7e71b1c1f2faf4
spotify 78e161924ebb42d4b2a4bde8f9cf5507 8dc73478654b4bc2bd7e71b1c1f2faf4

but it plays the song/artist I select where t his was failing last night.  Thanks for all of your help.

**Comment by bosyd** [comment]
Hey mate. I figure it out!!  Thanks for helping me I really appreciate your help and not I have Google Home integrated with Sonos :)

**Comment by jishi** [comment]
BTW, WARN messages are usually nothing to worry about. That particular message only means that it failed to renew it's event subscription from one of your players. Those are common, especially of you run this on a machine that sleeps. 

But if this is an always on machine, and you get this very often, you might have network issues with your Sonos (wireless interference).
