### ISSUE TITLE
Crashes when a speaker is not found

### ISSUE THREAD

**Issue by panigrah** [jishi/node-sonos-http-api#549]
When the join operation cannot find a speaker it crashes.

```
2017-08-25T11:49:22.931Z WARN Room day not found - can't make Living Room join it
./node-sonos-http-api/lib/sonos-http-api.js:88
    .then((response) => {
    ^

TypeError: Cannot read property 'then' of undefined
    at HttpAPI.requestHandler (./node-sonos-http-api/lib/sonos-http-api.js:88:5)
    at ./node-sonos-http-api/server.js:50:13
    at Server.finish (./node-sonos-http-api/node_modules/node-static/lib/node-static.js:111:13)
    at finish (./node-sonos-http-api/node_modules/node-static/lib/node-static.js:170:14)
    at ./node-sonos-http-api/node_modules/node-static/lib/node-static.js:144:17
    at FSReqWrap.oncomplete (fs.js:152:21)
```

This is because the `join` action handler returns null which should then return a `Promise.reject` in `lib/sonos-http-api.js` in `handleAction()`.

This should fix the problem
```
  function handleAction(options) {
    var player = options.player;

    if (!actions[options.action]) {
      return Promise.reject({ error: 'action \'' + options.action + '\' not found' });
    }

    // if action returns null - wrap in a rejection.
    var retval =  actions[options.action](player, options.values);
    if (!retval) {
      return Promise.reject({ error: 'action \'' + options.action + '\' failed see log for details.' });
    } else {
      return retval;
    }
  }
```

**Comment by jishi** [comment]
Thanks for reporting this. Although it might be useful to handle actions that doesn't return Promises, the real cause if this is that the grouping functions didn't return promises on errors. I fixed it by adjusting those instead. 

I'm gonna target Node 7.10.x eventually, which would have native support for async/await which would makes this much leaner to work with.
