### ISSUE TITLE
pause endpoint crash

### ISSUE THREAD

**Issue by johnlabarge** [jishi/node-sonos-http-api#557]
the /pauseall 
and {room}/pause endoints both crash the server with the following: 
ReferenceError: logger is not defined 

/Users/johnlabarge/node-sonos-http-api/lib/actions/pauseall.js:5
  logger.debug("pausing all players");
  ^

ReferenceError: logger is not defined
    at Object.pauseAll [as pauseall] (/Users/johnlabarge/node-sonos-http-api/lib/actions/pauseall.js:5:3)
    at handleAction (/Users/johnlabarge/node-sonos-http-api/lib/sonos-http-api.js:110:35)
    at HttpAPI.requestHandler (/Users/johnlabarge/node-sonos-http-api/lib/sonos-http-api.js:87:5)
    at /Users/johnlabarge/node-sonos-http-api/server.js:50:13
    at Server.finish (/Users/johnlabarge/node-sonos-http-api/node_modules/node-static/lib/node-static.js:111:13)
    at finish (/Users/johnlabarge/node-sonos-http-api/node_modules/node-static/lib/node-static.js:170:14)
    at /Users/johnlabarge/node-sonos-http-api/node_modules/node-static/lib/node-static.js:144:17
    at FSReqWrap.oncomplete (fs.js:153:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sonos-http-api@1.4.6 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@1.4.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johnlabarge/.npm/_logs/2017-10-07T01_21_19_744Z-debug.log

**Comment by johnlabarge** [comment]
Hmm may be docs issue. Looking into it.

**Comment by johnlabarge** [comment]
Just missing logger var sending PR.
