### ISSUE TITLE
Problem with presets returning an error

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#571]
Hi,

I have just done an update to the current version and it seems that now my presets aren't working.  I am getting this error:

{"status":"error","error":"Cannot read property 'avTransportUri' of undefined","stack":"TypeError: Cannot read property 'avTransportUri' of undefined\n    at c:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:55:17\n    at Array.reduce (native)\n    at groupWithCoordinator (c:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:53:6)\n    at c:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:113:12"}

**Comment by jishi** [comment]
Sounds like you didn't update the dependencies with npm install
--production as required after updating the source for the http-api

**Comment by pcgirl** [comment]
Thanks for getting back to me.  I have just changed this to be setup on my unraid system as a docker instead of on my windows pc.  It seems to be working now but I don't know how to get my Presets into it on my unraid.  Any ideas?


Thanks,
Jane Johnson



________________________________

**Comment by pcgirl** [comment]
I did the update again.  I extracted the files and then copied them over to the directory where I have all the files except for the Presets directory.  Then I did a npm install –production and it seemed to work and then I did npm start.  It seems to start fine and it sees the presets but I can’t seem to invoke them when I use the http://192.168.1.102:5005/presets/Jane in my web browser.  I can do other things like see the state of each room and change to a favorite but it doesn’t seem to like the preset command.  I just get an error.  In the command window it says presets can’t be found, but it found them fine when it started.
Your environment has been set up for using Node.js 4.6.0 (x64) and npm.

C:\Users\Jane>cd\ node
The system cannot find the path specified.

C:\Users\Jane>cd node
The system cannot find the path specified.

C:\Users\Jane>cd\

C:\>dir
Volume in drive C has no label.
Volume Serial Number is 521C-40FC

Directory of C:\

09/29/2016  01:15 PM    <DIR>          0cf871e50ac94f83e4673591a5
09/30/2016  12:24 PM    <DIR>          4a6b98dc894160620518ea
06/07/2016  11:05 AM    <DIR>          6b01a0a20d773a71499bf0c9
09/30/2016  10:25 AM    <DIR>          7a17967cbafd511e51b63d
06/07/2016  10:46 AM    <DIR>          7b6c443a201d2808238dbd00
09/30/2016  10:38 AM    <DIR>          8e15d3c713c8ccb0f558f57a1c2054
06/23/2016  12:59 PM    <DIR>          AMD
06/07/2016  10:52 AM    <DIR>          bc10fe6366ba8cd95b5298aa75
06/07/2016  12:15 AM            32,768 BCD_Backup
11/28/2017  03:23 PM    <DIR>          BusinessVision
06/08/2016  06:41 PM    <DIR>          CIMTEMP
11/23/2017  10:13 AM    <DIR>          CioniPayroll
06/08/2016  06:59 PM                10 csb.log
09/29/2016  11:06 AM    <DIR>          d0fd7a5d739d7ab13c
09/29/2016  10:51 AM    <DIR>          d6ad52af05c2297fbc7526b1b8ce61
09/29/2016  11:11 AM    <DIR>          dd3b2d695cdb0009f399999a80c5
11/08/2017  08:53 AM    <DIR>          easeus_tb_cloud
04/16/2015  12:56 AM    <DIR>          lan_W7
11/28/2017  03:26 PM    <DIR>          MyBV7Data
11/25/2016  10:19 AM    <DIR>          Node
12/22/2016  04:26 PM                34 node.bat
10/14/2016  05:45 PM    <DIR>          node_modules
10/14/2016  05:46 PM               932 npm-debug.log
07/13/2009  10:20 PM    <DIR>          PerfLogs
10/19/2017  01:04 PM    <DIR>          Program Files
11/28/2017  01:11 PM    <DIR>          Program Files (x86)
06/07/2016  03:31 PM           270,988 Reflect_Install.log
12/21/2016  09:12 AM    <DIR>          Sage
07/22/2016  04:06 PM                32 setup.log
06/08/2016  06:53 AM    <DIR>          System.sav
06/06/2016  03:55 PM    <DIR>          Users
10/27/2017  01:35 PM    <DIR>          Windows
               6 File(s)        304,764 bytes
              26 Dir(s)  187,700,514,816 bytes free

C:\>cd /node

C:\Node>dir
Volume in drive C has no label.
Volume Serial Number is 521C-40FC

Directory of C:\Node

11/25/2016  10:19 AM    <DIR>          .
11/25/2016  10:19 AM    <DIR>          ..
12/04/2017  02:52 PM    <DIR>          node-sonos
11/25/2016  10:19 AM               951 npm-debug.log
               1 File(s)            951 bytes
               3 Dir(s)  187,700,510,720 bytes free

C:\Node>cd node-sonos

C:\Node\node-sonos>npm start

> sonos-http-api@1.6.0 start C:\Node\node-sonos
> node server.js

2017-12-04T19:54:24.430Z INFO Presets loaded: { Dogs:
   { players:
      [ { roomName: 'Kitchen', volume: 16 },
        { roomName: 'Master Bedroom', volume: 15 },
        { roomName: 'Lauren\'s Room', volume: 15 },
        { roomName: 'Ryan\'s Bedroom', volume: 15 },
        { roomName: 'Workout Room', volume: 18 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'Q107' },
  example:
   { players:
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'My example favorite' },
  Jane:
   { players:
      [ { roomName: 'Kitchen', volume: 15 },
        { roomName: 'Master Bedroom', volume: 15 },
        { roomName: 'Lauren\'s Room', volume: 15 },
        { roomName: 'Ryan\'s Bedroom', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     playlist: 'Acoustic Chill' } }
2017-12-04T19:54:27.971Z INFO http server listening on port 5005
2017-12-04T19:55:02.901Z ERROR
  { error: 'action \'presets\' not found' }
2017-12-04T19:56:15.138Z ERROR
  { error: 'action \'presets\' not found' }
2017-12-04T20:03:50.232Z ERROR
  { error: 'action \'presets\' not found' }

Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++

**Comment by pcgirl** [comment]
Sorry but I noticed that I need to use preset not presets in the http:// reguest.  But is still gives an error.

status

"error"

error

"Cannot read property 'avTransportUri' of undefined"

stack

"TypeError: Cannot read property 'avTransportUri' of undefined\n at C:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:55:17\n at Array.reduce (native)\n at groupWithCoordinator (C:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:53:6)\n at C:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:113:12"



Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++

**Comment by pcgirl** [comment]
So I have updated to the latest node server.  I have deleted all files from my node-sonos directory and extracted your version and copied over the files.  I have done a npm install --production and then npm start.  Still I am getting the same error when trying to run a preset.

> 

error | "Cannot read property 'avTransportUri' of undefined"
-- | --
stack | "TypeError: Cannot read property 'avTransportUri' of undefined\n    at players.slice.reduce (C:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:55:18)\n    at Array.reduce (<anonymous>)\n    at groupWithCoordinator (C:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:53:6)\n    at promise.then (C:\\Node\\node-sonos\\node_modules\\sonos-discovery\\lib\\prototypes\\SonosSystem\\applyPreset.js:113:12)\n    at <anonymous>"

> 
Any ideas why this is still happening.

**Comment by jishi** [comment]
Are you including player names in your preset that no longer exists? I
thought I handled that nicely but when I look at the source, I don't really
see me handling that case, and would cause similar issues as you are
seeing.

On Dec 5, 2017 21:54, "pcgirl" <notifications@github.com> wrote:

So I have updated to the latest node server. I have deleted all files from
my node-sonos directory and extracted your version and copied over the
files. I have done a npm install --production and then npm start. Still I
am getting the same error when trying to run a preset.

error "Cannot read property 'avTransportUri' of undefined"
stack "TypeError: Cannot read property 'avTransportUri' of undefined\n at
players.slice.reduce (C:\Node\node-sonos\node_modules\sonos-discovery\lib\
prototypes\SonosSystem\applyPreset.js:55:18)\n at Array.reduce ()\n at
groupWithCoordinator (C:\Node\node-sonos\node_modules\sonos-discovery\lib\
prototypes\SonosSystem\applyPreset.js:53:6)\n at promise.then
(C:\Node\node-sonos\node_modules\sonos-discovery\lib\prototypes\SonosSystem\applyPreset.js:113:12)\n
at "

Any ideas why this is still happening.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jishi/node-sonos-http-api/issues/571#issuecomment-349327880>,
or mute the thread

**Comment by pcgirl** [comment]
Hi Jimmy,

No, the preset files have the same players in them that they had before except that I added a new player.  I can see the state of it when I do the command http://192.168.1.102:5005/state/Ryan’s<http://192.168.1.102:5005/state/Ryan's> Bedroom


Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++

**Comment by jishi** [comment]
You have a ' in the name? Hm, that has probably something to do with it. If
you remove that player from the preset it works?

I'm away on vacation so won't be able to fix it the coming two weeks.

**Comment by pcgirl** [comment]
Well I was running the presets before with a player named Lauren’s Room and it was working.  I will test it  without the new player and let you know.  Have a good vacation!

Thanks,

Jane Johnson

On Dec 5, 2017, at 10:06 AM, Jimmy Shimizu <notifications@github.com<mailto:notifications@github.com>> wrote:

You have a ' in the name? Hm, that has probably something to do with it. If
you remove that player from the preset it works?

I'm away on vacation so won't be able to fix it the coming two weeks.

**Comment by pcgirl** [comment]
Hi Jimmy,

So I took out the Ryan’s Bedroom from the preset and it did work.  However, the Lauren’s Room is still in the preset and it is working.  Does it have anything to do with the fact that I added this player recently?

Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++
