### ISSUE TITLE
ELIFECYCLE crash on OSX 10.13

### ISSUE THREAD

**Issue by MrZoidberg** [jishi/node-sonos-http-api#578]
Got a crash after node-sonos was working just fine for several days. nodejs 8.9.1, OSX 10.13

Here are console logs:
```
2017-12-10T23:15:35.620Z WARN resubscribing to sid uuid:RINCON_B8E9372EF2FA01400_sub0000000201 failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53623)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:35.621Z WARN resubscribing to sid uuid:RINCON_B8E9372EF2FA01400_sub0000000202 failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53624)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:35.721Z WARN resubscribing to sid uuid:RINCON_B8E9372EF2FA01400_sub0000000204 failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53625)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:35.722Z WARN resubscribing to sid uuid:RINCON_B8E9372EF2FA01400_sub0000000203 failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53626)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:35.922Z WARN resubscribing to sid uuid:RINCON_5CAAFD9F69A801400_sub0000000157 failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53627)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:35.965Z WARN resubscribing to sid uuid:RINCON_5CAAFD9F69A801400_sub0000000158 failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53628)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:36.114Z WARN resubscribing to sid uuid:RINCON_5CAAFD9F69A801400_sub0000000159 failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53629)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:36.115Z WARN resubscribing to sid uuid:RINCON_5CAAFD9F69A801400_sub0000000160 failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53630)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:36.116Z WARN resubscribing to sid uuid:RINCON_5CAAFD9F69A801400_sub0000000161 failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53631)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:40.621Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53633)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:40.621Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53634)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:40.732Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53635)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:40.733Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53636)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:40.923Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53637)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:40.967Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53638)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:41.118Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53639)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:41.119Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53640)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:41.119Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53641)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:45.630Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53644)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:45.630Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53645)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:45.739Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53646)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:45.739Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53647)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:45.925Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53648)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:45.977Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53649)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:46.119Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53650)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:46.120Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53651)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:46.120Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53652)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:50.632Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53664)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:50.632Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53665)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:50.741Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53666)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:50.741Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53667)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:50.936Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53668)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:50.987Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53669)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:51.125Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53670)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:51.125Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53671)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:51.125Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53672)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:55.633Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53674)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:55.633Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53675)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:55.748Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53676)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:55.748Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.102:1400 - Local (0.0.0.0:53677)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:55.946Z WARN resubscribing to sid null failed
  Error: connect ENETUNREACH 192.168.1.233:1400 - Local (0.0.0.0:53678)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-12-10T23:15:55.947Z ERROR Endpoint has probably died
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRNOTAVAIL 192.168.1.21:1905
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sonos-http-api@1.6.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-http-api@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mikhail/.npm/_logs/2017-12-10T23_15_55_968Z-debug.log
```

and here is /Users/mikhail/.npm/_logs/2017-12-10T23_15_55_968Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sonos-http-api@1.6.0~prestart: sonos-http-api@1.6.0
6 info lifecycle sonos-http-api@1.6.0~start: sonos-http-api@1.6.0
7 verbose lifecycle sonos-http-api@1.6.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle sonos-http-api@1.6.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Applications/node-sonos-http-api/node_modules/.bin:/Users/mikhail/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle sonos-http-api@1.6.0~start: CWD: /Applications/node-sonos-http-api
10 silly lifecycle sonos-http-api@1.6.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle sonos-http-api@1.6.0~start: Returned: code: 1  signal: null
12 info lifecycle sonos-http-api@1.6.0~start: Failed to exec start script
13 verbose stack Error: sonos-http-api@1.6.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid sonos-http-api@1.6.0
15 verbose cwd /Applications/node-sonos-http-api
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error sonos-http-api@1.6.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the sonos-http-api@1.6.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jishi** [comment]
Sorry for the late reply. Sounds like your macbook changed local IP address, and I don't handle that case. Will see if it's fixable.
