### ISSUE TITLE
Preset for Pandora station favorite no longer works

### ISSUE THREAD

**Issue by manonstreet** [jishi/node-sonos-http-api#581]
I have preset to play a favorite, which is a Pandora station which used to work, but broke sometime in the past few weeks/months.  The definition is as follows:

`{
  "players": [
    {
      "roomName": "Master Bedroom",
      "volume": 40
    }
  ],
  "playMode": {
    "crossfade": false
  },
  "pauseOthers": false,
  "favorite": "Sleepy Time",
  "sleep": 3600
}`

When invoking interactively in a browser, it returns:

{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error\n    at Object.invoke (/usr/local/lib/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)\n    at promise.then (/usr/local/lib/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:606:19)\n    at process._tickDomainCallback (internal/process/next_tick.js:129:7)"}

And the node output on the server is:

2017-12-26T16:43:15.053Z ERROR
  Error
    at Object.invoke (/usr/local/lib/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)
    at promise.then (/usr/local/lib/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:606:19)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

Regardless of which Pandora station I attempt to call, I always get the same result.  Interestingly I have no issue using presets for favorites linked to playlists (Spotify), nor do I have any trouble calling the favorite API endpoint directly against the zone followed by the sleep timer.

Any suggestions?

**Comment by jacobwtyler** [comment]
I'm getting a similar error when trying to invoke a station on Pandora.  My credentials are entered correctly on the server side in the settings.json file and in Pandora so that shouldn't be the problem but when I try to invoke any station, I get:
Browser Returns:
`{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.play (/sonos/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:443:15)\n    at pandoraAPI.then.then.then.then (/sonos/node-sonos-http-api/lib/actions/pandora.js:105:42)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)"}`
> 
and I get a popup message on the Sonos app which I've included a screenshot of here:
![image](https://user-images.githubusercontent.com/18349823/39483062-cf346614-4d36-11e8-96a5-38b3b373f005.png)

**Comment by jacobwtyler** [comment]
Anyone have any ideas on what might be going on here?  I've tried absolutely everything I can think of.  Luckily, WebCoRE (SmartThings Rules Engine that I use for automation) can play Pandora stations through SmartThings' (mostly broken) implementation of Sonos' API so I have a workaround but at this point I'm just frustrated with myself that I can't implement this one element of @jishi Sonos HTTP API.  Perhaps I should post in my own topic?  I don't want to double post though.  Just not sure if anyone is seeing this one since it's an older and only slightly related issue.
