### ISSUE TITLE
Cant find any playlists

### ISSUE THREAD

**Issue by bradc87** [jishi/node-sonos-http-api#604]
When I navigate to the /playlists url, this is the output: 

[]

Upon trying to start an existing playlist (which worked a couple days ago) i get this error:

2018-03-20T02:22:28.844Z ERROR 
  Error: Playlist not found
    at system.getPlaylists.then.then (/home/netadmin/sonos/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithPlaylist.js:13:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by bradc87** [comment]
UPDATE: It can not discover playlists in "My Sonos" from google music, but if I create a new playlist (button at bottom) in the My Sonos section, then it will recognize that.

**Comment by jishi** [comment]
This functionality only works with Sonos playlist. Since version 8.x, they introduced the "My Sonos" concept which sort of mashes everything together which makes it a bit hard to distinguish as a user. 

This is more evident in the desktop controller I think, where there is a clear distinction between the two.
