### ISSUE TITLE
log overflow when players get disconnected

### ISSUE THREAD

**Issue by cguthardt** [jishi/node-sonos-http-api#605]
I noticed that my Raspberry Pi had stopped working yesterday, so I did some checks and it turned out that the disk (sd card) was full: /var/log/node-sonos.log was over 3 GB in size.

I searched for the reason and was able to figure it out: Once a formerly connected player gets disconnected (powered off, taken to another room without being replugged right away), the log gets filled with entries like these:

```
2018-03-21T19:26:39.994Z WARN resubscribing to sid null failed
  Error: connect EHOSTUNREACH 192.168.0.128:1400
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

In one day I could see the log getting to 50 MB in size. Can this be disabled? I don't want to start to send the log to /dev/null, just repeating this message over and over again does not do any good.

**Comment by jishi** [comment]
Yeah, that is probably a bug. The system know of disconnected players, but
this subscription is probably not stopped accordingly. Either way, adding a
log rotation to the image is probably also a good idea.

**Comment by cguthardt** [comment]
Thanks for the fast answer. Yes, I know I can cure the symptoms with logrotate, regular deletion of old logs etc., but just wanted to let you know :-)

**Comment by mikkel75** [comment]
I have the same issue as I move one of my PLay1's around all the time...any fix?

**Comment by Axelaar** [comment]
The log entries that fill up syslog are similar to what was stated above.
Error: connect EHOSTUNREACH 192.168.168.19:1400
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
    WARN resubscribing to sid null failed
My Sonos is typically powered off until needed.

Is there any way to gracefully stop the subscription?

**Comment by TribuneX** [comment]
Any news here? I have also a growing log file with these entries.

**Comment by a-wenzel** [comment]
same here... 5 Days == 200+ MB logfile...

**Comment by cguthardt** [comment]
I added this to /etc/crontab and the problem is gone (at the cost of only having logs of the current day):

```
#to prevent overflowing node-sonos log when not all speakers powered on:
00 5    * * *  root  rm /var/log/node-sonos.log
```
