### ISSUE TITLE
error message in settings.json

### ISSUE THREAD

**Issue by badstraw360** [jishi/node-sonos-http-api#606]
First of all, Thank you very much for spending time reading this...

I've been trying to use the API, but I it's giving me an error message:

I have my settings.json located in ``` /home/pi/node-sonos-http-api-master/settings.json```

```
"spotify": {
	    "clientId": "783458734xxxx",
	    "clientSecret": "34598734958xxxx"
	  }
```
The error:

```
2018-03-26T22:07:23.685Z WARN Could not read file /home/pi/node-sonos-http-api-master/settings.json, ignoring.
  SyntaxError: Syntax error at line 1 column 11 of the JSON5 data. Still to read: ": { \"clientId\": \"7ed"
    at error (/home/pi/node-sonos-http-api-master/node_modules/json5/lib/json5.js:56:25)
    at Object.parse (/home/pi/node-sonos-http-api-master/node_modules/json5/lib/json5.js:511:13)
    at tryLoadJson (/home/pi/node-sonos-http-api-master/lib/helpers/try-load-json.js:8:33)
    at Object.<anonymous> (/home/pi/node-sonos-http-api-master/settings.js:29:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
2018-03-26T22:07:24.478Z INFO Presets loaded: { example: 
   { players: 
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false } }
2018-03-26T22:07:28.866Z INFO http server listening on 0.0.0.0 port 5005

```
What am I missing?

**Comment by jishi** [comment]
Hi, you are missing the initial enclosing of curly brackets, {}

Json always start with curly brackets to annotate the parent object. Just
wrap the whole content of your file with additional brackets and it should
be fine.

**Comment by badstraw360** [comment]
Thank you very much!!!

I was listening to a playlist but then I tried to send the command again and I got this error: 

```

Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
    at Object.invoke (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
    at Player.trackSeek (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:547:15)
    at player.coordinator.addURIToQueue.then (/home/pi/node-sonos-http-api-master/lib/actions/spotify.js:38:56)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)


```

I appreciate your help.

**Comment by jishi** [comment]
Hm, seems like it fails to skip to the last added track in the queue. What was the source you were playing before you called that action? 

Was it a radiostation, or was it spotify controlled form the spotify app (spotify direct/connect)?

**Comment by badstraw360** [comment]
Since I'm using homeassistant, the source that I was playing is spotify connect, it was a custom 
playlist. It's weird because I was getting audio from the speakers, but I couldn't see it sync with my computer or the app on my phone, like if it wasn't playing any song at all..  I had to connect to my speakers using the app to stop the audio, then I couldn't make it work again. 

Should I send a different command besides that one?

**Comment by jishi** [comment]
Spotify Connect works a bit differently, since it doesn't use the queue. I think that's where the error stems from... I'd consider it a bug, if you invoke an action that puts stuff on queue you probably want the player to switch over to queue playback. There is a very crude way of doing that with an http call, but it's not very intuitive. You basically need to set the avtransport to match `x-rincon-queue:[UUID of player]:0`, so you need to know the UUID first which you can only get from the zones command right now.

**Comment by jishi** [comment]
Or no, actually, it is supposed to do that https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/spotify.js#L32-L34

But I think Spotify Connect is using the same prefix, but it doesn't end in #0 and that confuses the code.

**Comment by badstraw360** [comment]
So how can I play a playlist without getting the error? Would that be possible in the meantime?

**Comment by VleeG** [comment]
@badstraw360, I'm having the same issue, have you been able to work around this?

**Comment by rummens** [comment]
Any update on this? Playlists work fine for me, but I cannot start a track: http:/[...]/now/spotify:track:4vy5WRcqDlmSoiK3LoPfH7:

**Comment by acatoire** [comment]
On my setup, playlist never works, and album work only if spotify connect is not already playing.
Starting a radio from the sonos app do cancel spotify connect then album works again.

**Comment by acatoire** [comment]
Also sending a tunein/play/xxxxx cancel the spotify connect then a spotify/now/spotify:album:xxxxx do work
