### ISSUE TITLE
Pandora, play: Got status 500 when invoking /MediaRenderer/AVTransport/Control

### ISSUE THREAD

**Issue by hypermoose** [jishi/node-sonos-http-api#623]
Trying to play a station by name in my pandora list.  Debugging through the code search works fine but when it attempts to start playback it fails with a 500,

**Comment by jishi** [comment]
Could you please provide more details on your debugging? 

If you run it with the environment variable `NODE_LOG_LEVEL=trace` on, could you try and intercept the pandora invocation and email to me? (jimmy at shimizu dot se)

For linux/Mac, do:

`NODE_LOG_LEVEL=trace npm start`

For Windows Powershell you need to do two commans, do 
`$env:NODE_LOG_LEVEL='trace'`
`npm start`

**Comment by hypermoose** [comment]
Here is the request and the failure.  I'm getting similar errors with Spotify as well, FYI.

2018-06-25T14:15:10.849Z TRACE http://192.168.1.155:1400/MediaRenderer/AVTransport/Control urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><CurrentURI>pndrradio:3952120410954390567?sn=2,&quot;title&quot;:&quot;ZZ Top Radio&quot;,&quot;albumArtUri&quot;:&quot;http://mediaserver-cont-dc6-2-v4v6.pandora.com/images/public/rovi/albumart/6/2/0/8/075992738026_500W_500H.jpg&quot;</CurrentURI><CurrentURIMetaData>&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;
        xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;
        &lt;item id=&quot;OOOX3952120410954390567&quot; parentID=&quot;0&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;ZZ Top Radio&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;
        &lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON3_jojo@jojo-graphics.com&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</CurrentURIMetaData></u:SetAVTransportURI></s:Body></s:Envelope>
2018-06-25T14:15:10.863Z ERROR
  Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
    at Object.invoke (D:\code\node-sonos-http-api\node_modules\sonos-discovery\lib\helpers\soap.js:99:10)
    at Player.setAVTransport (D:\code\node-sonos-http-api\node_modules\sonos-discovery\lib\models\Player.js:722:15)
    at pandoraAPI.then.then.then (D:\code\node-sonos-http-api\lib\actions\pandora.js:104:42)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by jishi** [comment]
Did you recently re-add Pandora? Or is this a new setup and it has never
worked? There might be a difference on how the Pandora accounts and their
Metadata is used nowadays, I've seen similar change for Sirius, but I can't
really verify it since I don't have those services in Sweden. I would need
help with some packet dumps from the official controller from someone in
the states.

**Comment by hypermoose** [comment]
It did work.   I don't think we re added it.   I can get you some wireshark traces on the sonos controller if that will help figure it out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jishi** [comment]
That would be great if you could provide. I primarily need the soap payload
that is sent when it invokes tee setavtransporturi call

**Comment by jplourde5** [comment]
Seems like we saw in an earlier post that the metadata changed dramatically. It would be great if you can save a Pandora station as a Sonos Favorite, launch the favorite through the node-songs-http-api, and capture the metadata.

**Comment by hypermoose** [comment]
Here is a network capture of my Win10 PC’s Sonos controller telling one of my Sonos speakers to play the “Journey Radio” station from Pandora.

POST /MediaRenderer/AVTransport/Control HTTP/1.1
CONNECTION: close
ACCEPT-ENCODING: gzip
HOST: 192.168.1.155:1400
USER-AGENT: Linux UPnP/1.0 Sonos/43.3-54020 (WDCR:Microsoft Windows NT 10.0.17692)
CONTENT-LENGTH: 1117
CONTENT-TYPE: text/xml; charset="utf-8"
X-SONOS-TARGET-UDN: uuid:RINCON_000E58F9D1B201400
SOAPACTION: "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI"

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><CurrentURI>x-sonosapi-radio:ST%3a1087871747056852007?sid=236&amp;flags=8300&amp;sn=1</CurrentURI><CurrentURIMetaData>&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;100c206cST%3a1087871747056852007&quot; parentID=&quot;10082064myStations&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Journey Radio&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast.#station&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON60423_X_#Svc60423-7c82821-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</CurrentURIMe

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jishi** [comment]
Ah, yes. Looks like the account identification info is now different, `SA_RINCON60423_X_#Svc60423-7c82821-Token`

Sonos has also removed the ability to get a hold of that info easily, so it might need to be "learnt" now over time (unless I can figure out a way of finding it by other means).

**Comment by hypermoose** [comment]
I was able to follow spotifyDef.js’s format and method for getServiceToken and get pandora working again.  Also to get spotify working again I had to find the value of SN= since the Sonos /status/accounts page isn’t there.   Pandora hardcodes it, is that a constant by chance?  My Spotify is 14 curious what others might be.

Gary

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jishi** [comment]
@hypermoose Yes, the sn is supposedly static (it is also related to the 60423 number). I think it is possible to infer it from a UPnP call called GetServiceList, but I'll have to double check it.

**Comment by hypermoose** [comment]
I got both Pandora and Spotify working again and issued two PRs, one here and a dependent one in node-sonos-discovery.  Please take a look when you have time

**Comment by hypermoose** [comment]
@jishi ping?  Can you take a look at my two pull requests and see if they meet the bar

**Comment by jplourde5** [comment]
I tested the Pandora fix and it works. Thanks for that. I no longer have a Spotify account that I can test with.
