### ISSUE TITLE
Spotify fails, Apple Music works fine, what do i have wrong?

### ISSUE THREAD

**Issue by clarknet** [jishi/node-sonos-http-api#624]
Before writing this, I looked for a solution, but could not find one... I have used this API for apple music for a long time. Works great.  I now am using Spotify on Sonos in addition to Apple Music, but can NOT get any spotify request to work (play, search, etc)  I have added the required credentials for spotify to my settings.json file.

Here is an example of using the same Search with Apple and Spotify....

1. Using Apple for search works fine
HTTP://localhost:5005/Living/musicsearch/apple/song/red+hot+chili+peppers
Success, plays searched results

2. Using spotify with same search, it fails
HTTP://localhost:5005/Living/musicsearch/spotify/song/red+hot+chili+peppers

**Results in the browser:**

{"status":"error","error":"401 - [object Object]","stack":"StatusCodeError: 401 - [object Object]\n    at new StatusCodeError (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request-promise/lib/errors.js:26:15)\n    at Request.RP$callback [as _callback] (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request-promise/lib/rp.js:68:32)\n    at Request.self.callback (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request/request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request/request.js:1079:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}

**in my terminal window i get:** 

macbooktinaprc2:jishi-node-sonos api pclark$ npm start

> sonos-http-api@1.0.1 start /Users/pclark/Sonos Stuff/jishi-node-sonos api
> node server.js

2018-06-25T18:14:32.151Z INFO Presets loaded: {}
2018-06-25T18:14:32.169Z INFO http server listening on port 5005
2018-06-25T18:15:18.532Z ERROR 
  StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/pclark/Sonos Stuff/jishi-node-sonos api/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by jishi** [comment]
Sorry for the late answer. This seems to be related to the credentials you use for spotify. Are you sure those are valid?

**Comment by clarknet** [comment]
Thanks for the following, its been a while since I came back to this project.  So I have tripled checked credentials for spotify account I use with Sonos. Here is the test of my settings file... I used the ### characters to hide my full secret for this post. Stored in root directory as settings.json. See Screen shot. Using Voicers account works fine, which somewhat validates settings file. Am I missing something here? 

{
	  "spotify": {
	    "clientId": "038d5fa23c7948eca99d05c7691e1da5",
	    "clientSecret": "827e51fb59a340c38a18da######d"
	  },
	  "voicerss": "1fa9562a22994991b3176e44c7d6062f"
}


Any further help appreciated - still getting same errors as first post. 
-Paul Clark




![image](https://user-images.githubusercontent.com/6515606/42946356-a994795e-8b38-11e8-8e85-a0ed7a0d61cc.jpeg)

**Comment by jishi** [comment]
The `http://localhost:5005/Livingroom/spotify/next/spotify:track:4LI1ykYGFCcXPWkrpcU7hn` doesn't require any credentials, but should only require a valid Spotify account added to your system. Are you sure that is the case? You could also try removing and re-adding it again. 

If you have a problem with your spotify account on Sonos, the search would also fail. The only thing the credentials are for, is to get access to the Spotify search API. playback still uses the account added into our Sonos system.

**Comment by clarknet** [comment]
Thanks for the rapid response. Very helpful. I will double check Sonos / Spotify settings again, and will try the  removing/re-adding of the account.
