### ISSUE TITLE
Presets not working

### ISSUE THREAD

**Issue by IsaTTeN** [jishi/node-sonos-http-api#627]
Hello

I´m trying to setup a presets but I´m unable to do it

I create a file in home/pi/node-sonos-http-api/presets/ , named dia.json with this code:

{
  "players": [
    {
      "roomName": "Cocina",
      "volume": 10
    },
    {
      "roomName": "Salon",
      "volume": 15
    }
  ],
  "playMode": {
    "shuffle": true,
    "repeat": "all",
    "crossfade": false
  },
  "pauseOthers": false,
  "favorite": "Domoticz"
}

When I execute http://192.168.2.185:5005/preset/dia I have this output:
{"status":"error","error":"Favorite not found","stack":"Error: Favorite not found\n    at /home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithFavorite.js:21:15\n    at process._tickDomainCallback (node.js:407:9)"}

What is wrong???

Is it maybe because the favorite isn´t well configurated in Sonos? If I execute: http://192.168.2.185:5005/Cocina/favorite/Domoticz I get this error:
{"status":"error","error":"Favorite not found","stack":"Error: Favorite not found\n    at /home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithFavorite.js:21:15\n    at process._tickDomainCallback (node.js:407:9)"}
But if I execute this: http://192.168.2.185:5005/Cocina/playlist/Domoticz  it is ok

Thank you in advance

Best regards

**Comment by IsaTTeN** [comment]
I had some mistakes and I solved but I have still an error. Any ideas?

**Comment by IsaTTeN** [comment]
Solved for myself, was a problem with the favorite
