### ISSUE TITLE
avTransportUri

### ISSUE THREAD

**Issue by heubi76** [jishi/node-sonos-http-api#641]
Hello
Having a sonos speaker outside wich is not always online.
Having a smart house and different modes for the sonos.
If I use preset with all speakers and "garden" is not connected the avTransportUri fault is showing up.
Is it possible to go around this anyhow?
Thanx for a quick answer.
heubi

**Comment by heubi76** [comment]
TypeError: Cannot read property 'avTransportUri' of undefined                                                                                                                                                              
    at players.slice.reduce (/sonos/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:55:18)                                                                                                            
    at Array.reduce (<anonymous>)                                                                                                                                                                                            
    at groupWithCoordinator (/sonos/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:53:6)                                                                                                             
    at promise.then (/sonos/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:113:12)                                                                                                                   
(node:50) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
