### ISSUE TITLE
Error with spotify musicsearch 

### ISSUE THREAD

**Issue by ADN182** [jishi/node-sonos-http-api#649]
Hi,

I get an error when i try to get "/musicsearch/spotify/song/red+hot+chili+peppers" like in readme file.

I have fill my Spotify Client ID and Secret ID and this request :
"/musicsearch/spotify/playlist/Hits du Moment" work's perfectly but not with a song, album don't display error but never match.

Error Message : 
{"status":"error","error":"Cannot read property 'indexOf' of undefined","stack":"TypeError: Cannot read property 'indexOf' of undefined\n    at /app/lib/music_services/spotifyDef.js:229:34\n    at Array.reduce (native)\n    at Object.loadTracks [as tracks] (/app/lib/music_services/spotifyDef.js:228:50)\n    at loadTracks (/app/lib/actions/musicSearch.js:148:36)\n    at getAccountId.then.then (/app/lib/actions/musicSearch.js:239:24)\n    at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:584:18)\n    at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/main/async.js:15:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"}

**Comment by ADN182** [comment]
Hi, After  cloning your Repo, i have change coutry information in spotifyDef.js to have my country directly inside ('FR') and it's work's now correctly.

So i supposed some problem when retrieved country.

**Comment by ADN182** [comment]
In fact, just applying the fix in #647 (https://github.com/jishi/node-sonos-http-api/pull/647, thank @mreishus ) solved the problem (without changing country). I have also make a modification for Album in spotifyDef.js typo error : 

Ligne 19 : 
               album:   'https://api.spotify.com/v1/search?type=album&limit=1&q=album:',
by 
               album:   'https://api.spotify.com/v1/search?type=album&limit=1&q=',
