### ISSUE TITLE
TypeError: Buffer.alloc is not a function on node 5.6.0

### ISSUE THREAD

**Issue by Timvdv** [jishi/node-sonos-http-api#651]
Hey guys,

Thanks for this amazing API. I'm running this on a server with some old NodeJS processes which I can't update. 5.6.0 is the highest node version I can go.

Everything seems to work except for voice messaging.

When I call /say/blabla I'm getting the following error:

```
> sonos-http-api@1.6.3 start /home/tim/node-sonos-http-api
> node server.js

2018-09-22T13:38:54.436Z INFO Presets loaded: { example:
   { players:
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false } }
2018-09-22T13:38:54.961Z INFO http server listening on 0.0.0.0 port 5005
2018-09-22T13:39:21.009Z ERROR
  TypeError: Buffer.alloc is not a function
    at FileTokenizer.AbstractTokenizer (/home/tim/node-sonos-http-api/node_modules/strtok3/lib/AbstractTokenizer.js:7:33)
    at new FileTokenizer (/home/tim/node-sonos-http-api/node_modules/strtok3/lib/FileTokenizer.js:23:28)
    at /home/tim/node-sonos-http-api/node_modules/strtok3/lib/index.js:38:24
    at tryCatch (/home/tim/node-sonos-http-api/node_modules/es6-promise/dist/es6-promise.js:409:12)
    at invokeCallback (/home/tim/node-sonos-http-api/node_modules/es6-promise/dist/es6-promise.js:424:13)
    at publish (/home/tim/node-sonos-http-api/node_modules/es6-promise/dist/es6-promise.js:398:7)
    at flush (/home/tim/node-sonos-http-api/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickDomainCallback (node.js:423:13)

```

I tried upgrading my NodeJS version and that fixes it. But when I upgrade NodeJS the other apps on the server won't run.

If you guys know how to fix this it would be highly appreciated.

Thanks,

Tim

**Comment by jishi** [comment]
Seems to be some dependency that is using some newer buffer functions.
Which version do you need to run, and what did you upgrade to?

**Comment by Timvdv** [comment]
@jishi Thanks for the quick response! I upgraded to the latest stable NodeJS version using "n stable" (just for testing purposes) the latest version did not give me this error. I need to run it on 5.6.0 because that's the latest version supported in other applications.

**Comment by jishi** [comment]
It's supposed to run on 4+, might need to pin some depenency to an earlier
version since it's not my code that contains the unsupported buffer calls.

But requiring version 5 is a bit weird since it's not an LTS version, 6
would make more sense. Worst case you can have multiple versions installed
and run es h application with its own version.

**Comment by Timvdv** [comment]
Aww okay 5.6 is really the best option for me. In 6+ my other apps do not work anymore. I'll just try to play with nvm and try to get both processes running on different versions. Thanks.
