### ISSUE TITLE
error when starting server

### ISSUE THREAD

**Issue by bednim** [jishi/node-sonos-http-api#656]
hi there, so i have installed node-sonos-http-api and when i do npm start I get this. What do I have to do to get it started without any hickups? I run it on raspi zero with node-red installed. Thank you!

`pi@raspberrypi:~/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9 $ npm start

> sonos-http-api@1.0.1 start /home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9
> node server.js

2018-10-29T20:54:39.746Z INFO no settings file found, will only use default settings
2018-10-29T20:54:41.269Z INFO Presets loaded: { example: 
   { players: 
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false,
     favorite: 'My example favorite' } }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/helpers/try-download-tts.js:11:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/actions/say_v2.js:7:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/actions/say_v2.js:17:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at files.map.filter.forEach (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/helpers/require-dir.js:18:8)
    at Array.forEach (<anonymous>)
    at module.exports (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/server.js:44:11) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './settings.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/actions/sayall.js:11:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at files.map.filter.forEach (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/helpers/require-dir.js:18:8)
    at Array.forEach (<anonymous>)
    at module.exports (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/helpers/require-dir.js:17:6)
    at new HttpAPI (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/lib/sonos-http-api.js:45:3)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9/server.js:44:11) code: 'MODULE_NOT_FOUND' }
2018-10-29T20:54:41.655Z INFO http server listening on port 5005
http://localhost:5005/zones

`

**Comment by jishi** [comment]
Sorry, I missed this issue. 

Seems like the system gets confused because of the way you installed this. You are supposed to unzip it into a folder and invoke `npm install` within that folder. Looks like you have used npm install with a github url to install this as a dependency (to node-red?) which doesn't seem to work.

**Comment by bednim** [comment]
> Sorry, I missed this issue.
> 
> Seems like the system gets confused because of the way you installed this. You are supposed to unzip it into a folder and invoke `npm install` within that folder. Looks like you have used npm install with a github url to install this as a dependency (to node-red?) which doesn't seem to work.

Hi jishi, thank you for getting back to me. I have unzipped it in node-red folder and did npm install --production as per your github. I indeed use node red. Can I use this alongside node-red? How should I install it correctly? 

thank you

**Comment by Marty56** [comment]
Same behavior when installing Docker image on Synology.
Additionally when I am trying to access the server via http commands I receive and error that states that it cannot establish a connection to the server (translated from German).

**Comment by jishi** [comment]
@Marty56 sounds like a completely different problem. Did you ensure that you ran it with `--network=host` ?

**Comment by jishi** [comment]
@bednim Your explanation of your install sounds about right, but the error output tells a different story. I don't see why it would reside in a node_modules folder:

`home/pi/.node-red/node_modules/jishi-node-sonos-http-api-0d03be9`

I don't know what node-red is either, so I can't tell you if it is supported or not.

**Comment by Marty56** [comment]
@jishi: I did not run it as host. Now it is working. 
Many thanks for your support.

**Comment by bednim** [comment]
@jishi thanks for coming back to me. Sorry to keep bothering you - what should be correct instalation path please? Thank you

**Comment by jishi** [comment]
@bednim Doesn't matter which path you install it on, but it should not be under another `node_modules` folder, because that might confuse the module resolution system, or you install the dependencies wrong.

Just unzip or `git clone` into `/home/pi/sonos-http-api` or something, and then run `npm install` in there.

**Comment by bednim** [comment]
Great, I'll do that later today! Thank you!
