### ISSUE TITLE
Playing m3u stream with setavtransporturi

### ISSUE THREAD

**Issue by muuuh** [jishi/node-sonos-http-api#670]
Hi,

I've tried to play an m3u stream, like
http://192.168.188.2:5005/Speaker1/setavtransporturi/http%3A%2F%2Fmp3stream7.apasf.apa.at%3A8000%2Flisten.pls

I get the following error:
```
2019-01-06T12:59:35.000Z ERROR 
  Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
    at Object.invoke (/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
    at Player.setAVTransport (/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:727:15)
    at Object.setAVTransportURI (/node-sonos-http-api/lib/actions/setavtransporturi.js:3:17)
    at handleAction (/node-sonos-http-api/lib/sonos-http-api.js:117:35)
    at HttpAPI.requestHandler (/node-sonos-http-api/lib/sonos-http-api.js:94:21)
    at /node-sonos-http-api/server.js:50:13
    at Server.finish (/node-sonos-http-api/node_modules/node-static/lib/node-static.js:111:13)
    at finish (/node-sonos-http-api/node_modules/node-static/lib/node-static.js:170:14)
    at /node-sonos-http-api/node_modules/node-static/lib/node-static.js:144:17
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Could you please give me a hint what's wrong?
Best regards,

**Comment by jishi** [comment]
What does the pls include? Is it like a radio station? I'm guessing it
needs to be invoked via a different kind of url. The only way to deal with
it today would be to add it as a manual radio station, and then mark that
as a favorite and start that favorite.
