### ISSUE TITLE
Constant error in logs

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#692]
I am getting this constant error in the logs even if a TTS request wasn't sent.
2019-04-16T17:12:54.915Z ERROR

{ error: 'action \'tts\' not found' }

**Comment by pcgirl** [comment]
Any ideas what is going on with this error?  I get it constantly in my logs:
![image](https://user-images.githubusercontent.com/10760412/57545363-12a1f200-7328-11e9-988c-608be7532854.png)

**Comment by jishi** [comment]
You have something calling the API every 20 minutes with a faulty URL, namely something like `/room/tts/xxxxxxx` which isn't a valid action. Doesn't make sense to put that in the log though, but you should try to figure out what it is that you have setup that would make these invocations.

**Comment by pcgirl** [comment]
I don't have any TTS using the sonos speakers.  How would I find this?

**Comment by jishi** [comment]
One alternative since it is every 20 minute would be to run the tcpdump
command and wait to figure out the src ip. It would be possible to add
logging in the api as well but is a bit more work for me :)

If you run tcpdump for dst port 5005 when you expect a request to come in
it should be fairly easy to pinpoint I think.

**Comment by pcgirl** [comment]
Now this error is showing up in the logs:  How do I run tcpdump?


Error: connect EHOSTUNREACH 192.168.1.20:1400
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
2019-05-11T18:39:52.031Z WARN resubscribing to sid null failed
Error: connect EHOSTUNREACH 192.168.1.20:1400
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
2019-05-11T18:39:52.031Z WARN resubscribing to sid null failed
Error: connect EHOSTUNREACH 192.168.1.20:1400
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
2019-05-11T18:39:52.031Z WARN resubscribing to sid null failed
Error: connect EHOSTUNREACH 192.168.1.20:1400
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
2019-05-11T18:39:53.950Z WARN resubscribing to sid null failed
Error: connect EHOSTUNREACH 192.168.1.16:1400
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
2019-05-11T18:39:53.951Z WARN resubscribing to sid null failed

Thanks,
Jane Johnson
++++++++++++++++++
A+ Computer Services
(905) 317-0540
++++++++++++++++++

________________________________

**Comment by jishi** [comment]
Thats a different error. It tries to resubscribe for events to a player IP that doesn't seem to exist anymore. 

Maybe your players are changing IP and the API doesn't handle it gracefully. You still see all your players, and their state (currently playing source, time etc) is correct?

**Comment by pcgirl** [comment]
OK, I just did a Sonos update and then restarted the docker.  The log isn't showing any errors....yet.  I will watch it and see what happens.  How do I run tcpdump?

Thanks,
Jane Johnson

________________________________

**Comment by jishi** [comment]
You're gonna have to look that up on your own. It's a way to broad topic for me to assist with :)
