### ISSUE TITLE
Script not starting

### ISSUE THREAD

**Issue by cynster** [jishi/node-sonos-http-api#702]
Everything worked fine before. Did not change anything, but might 've been caused by an update. Not sure though.

**debug log:**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sonos-http-api@1.6.8~prestart: sonos-http-api@1.6.8
6 info lifecycle sonos-http-api@1.6.8~start: sonos-http-api@1.6.8
7 verbose lifecycle sonos-http-api@1.6.8~start: unsafe-perm in lifecycle true
8 verbose lifecycle sonos-http-api@1.6.8~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/node-sonos-http-api/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle sonos-http-api@1.6.8~start: CWD: /home/pi/node-sonos-http-api
10 silly lifecycle sonos-http-api@1.6.8~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle sonos-http-api@1.6.8~start: Returned: code: 1  signal: null
12 info lifecycle sonos-http-api@1.6.8~start: Failed to exec start script
13 verbose stack Error: sonos-http-api@1.6.8 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid sonos-http-api@1.6.8
15 verbose cwd /home/pi/node-sonos-http-api
16 verbose Linux 4.19.42-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.16.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error sonos-http-api@1.6.8 start: `node server.js`
22 error Exit status 1
23 error Failed at the sonos-http-api@1.6.8 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jishi** [comment]
What happens if you just invoke `node server.js` ?
