### ISSUE TITLE
"Got status 500 when invoking /MediaRenderer/AVTransport/Control"

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#704]
Everything was working and then all of a sudden I am getting an error when trying to play presets using the http://192.168.1.100:5005/preset/Jane.  This is what is showing in the log:

> sonos-http-api@1.6.8 start /app
> node server.js

2019-06-27T14:29:13.566Z INFO Presets loaded: { Dogs:
{ players:
[ { roomName: 'Kitchen Sonos', volume: 17 },
{ roomName: 'Master Sonos', volume: 16 },
{ roomName: 'Laurens Sonos', volume: 16 },
{ roomName: 'Workout Room', volume: 18 },
{ roomName: 'Ryans Sonos', volume: 18 },
{ roomName: 'Master Bathroom', volume: 16 } ],
pauseOthers: false,
favorite: 'KX 94.7' },
Jane:
{ players:
[ { roomName: 'Kitchen Sonos', volume: 15 },
{ roomName: 'Master Sonos', volume: 15 },
{ roomName: 'Laurens Sonos', volume: 15 },
{ roomName: 'Ryans Sonos', volume: 15 },
{ roomName: 'Master Bathroom', volume: 15 } ],
playMode: { shuffle: true, repeat: 'all', crossfade: true },
pauseOthers: false,
playlist: 'Laidback Acoustic' },
speakers:
{ players:
[ { roomName: 'Kitchen Sonos', volume: 35 },
{ roomName: 'Master Sonos', volume: 35 },
{ roomName: 'Laurens Sonos', volume: 35 },
{ roomName: 'Ryans Sonos', volume: 35 },
{ roomName: 'Workout Room', volume: 35 },
{ roomName: 'Master Bathroom', volume: 30 } ],
pauseOthers: false } }
2019-06-27T14:29:14.222Z INFO http server listening on 0.0.0.0 port 5005
2019-06-27T14:29:33.890Z ERROR
Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
at Object.invoke (/app/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
at Player.setAVTransport (/app/node_modules/sonos-discovery/lib/models/Player.js:727:15)
at promise.then (/app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:61:40)
2019-06-27T14:31:07.751Z WARN resubscribing to sid undefined failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:31:07.751Z WARN resubscribing to sid undefined failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:31:11.841Z WARN resubscribing to sid undefined failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:31:15.937Z WARN resubscribing to sid undefined failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:31:46.810Z ERROR
Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control
at Object.invoke (/app/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
at Player.setAVTransport (/app/node_modules/sonos-discovery/lib/models/Player.js:727:15)
at promise.then (/app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:61:40)
2019-06-27T14:33:06.527Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:33:06.528Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:33:10.623Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:33:14.719Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:35:05.312Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:35:05.312Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:35:05.312Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:35:05.312Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:35:09.407Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:35:09.407Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:35:13.503Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:37:04.095Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:37:04.095Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:37:08.191Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:37:12.287Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:39:02.880Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:39:02.881Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:39:06.977Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)
2019-06-27T14:39:11.073Z WARN resubscribing to sid null failed
Error: read ECONNRESET
at exports._errnoException (util.js:1020:11)
at TCP.onread (net.js:580:26)

**Comment by jishi** [comment]
Error: read ECONNRESET indicates that the API is trying to connect to the wrong IP of a player. Are your players switching IPs for some reason?
