### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by besynnerlig** [jishi/node-sonos-http-api#705]
On Ubuntu 18.04.2 LTS
npm 6.9.2
Tried using node/4.9.1, node/6.4.0, node/6.17.1, node/8.16.0, node/10.16.0

Clean installation.

```
cd ~
git clone https://github.com/jishi/node-sonos-http-api node-sonos-http-api
cd node-sonos-http-api
npm install --production
npm start
```

Results in:
```
besynnerlig@stork:~/node-sonos-http-api$ node server.js
2019-06-28T08:18:59.105Z INFO Could not find file /home/besynnerlig/node-sonos-http-api/settings.json
2019-06-28T08:18:59.179Z INFO Presets loaded: { example:
   { players:
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false } }
2019-06-28T08:18:59.547Z INFO http server listening on 0.0.0.0 port 5005
2019-06-28T08:18:59.909Z ERROR
  TypeError: Cannot read property 'length' of undefined
    at XmlEntities.exports.XmlEntities.XmlEntities.decode (/home/besynnerlig/node-sonos-http-api/node_modules/sonos-discovery/node_modules/html-entities/lib/xml-entities.js:48:14)
    at NotificationListener.notificationHandler (/home/besynnerlig/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:264:42)
    at emitTwo (events.js:111:20)
    at NotificationListener.emit (events.js:191:7)
    at parseLastChange.then (/home/besynnerlig/node-sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:125:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
2019-06-28T08:18:59.925Z ERROR
  TypeError: Cannot read property 'length' of undefined
    at XmlEntities.exports.XmlEntities.XmlEntities.decode (/home/besynnerlig/node-sonos-http-api/node_modules/sonos-discovery/node_modules/html-entities/lib/xml-entities.js:48:14)
    at NotificationListener.notificationHandler (/home/besynnerlig/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:264:42)
    at emitTwo (events.js:111:20)
    at NotificationListener.emit (events.js:191:7)
    at parseLastChange.then (/home/besynnerlig/node-sonos-http-api/node_modules/sonos-discovery/lib/NotificationListener.js:125:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Any suggestion how to solve this is highly appreciated. Thanks.

**Comment by besynnerlig** [comment]
I installed node-sonos-http-api in a new docker container with no issues at all. Problem solved.

**Comment by tischnu** [comment]
Just in case someone gets here searching for this error:
I had the same error on a clean install using the latest Release code (v1.4.3). Cloning into latest git version did the trick.

**Comment by Axelaar** [comment]
Struggling with the same issue today.  v1.4.3,  Node.js is version 10.23.1 (I tried with node.js v8 but could not get that to work at all).  Running on a Raspberry Pi (Buster).  
@tischnu , you say "Cloning into latest git version did the trick."  I am not a programmer - what did you do to get it to work?

**Comment by Axelaar** [comment]
The problem could be solved by modifying the content of the package.json file as per [https://npmjs.com/advisories/782](url).  Changed line 25 to v1.7.3.tar.gz,
Apparently the issue was resolved 2 years ago, searching for this fix using google did not get me anywhere.
