### ISSUE TITLE
First use issue 

### ISSUE THREAD

**Issue by Explorer-OL** [jishi/node-sonos-http-api#714]
Hi,

I am fairly new on this technology so please receive my apologies if I spell an issue as an obvious wrong installation.

I installed node.js and this sonos http api controller, when launching it I get some error messages, the server is running and can be accessed but music arts are not displayed and use of any command button make the server crash.

I am running this on a Windows 10 PC.

Any advice for the junior I am?
Thanks
OL

C:\Users\olivi\Downloads\Sonos API remote access\node-sonos-web-controller-master>node server.js
http server listening on port 8070
(node:2128) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at isRadio (C:\Users\olivi\Downloads\Sonos API remote access\node-sonos-web-controller-master\node_modules\sonos-discovery\lib\prototypes\Player\getUriType.js:4:14)
    at Player.getUriType (C:\Users\olivi\Downloads\Sonos API remote access\node-sonos-web-controller-master\node_modules\sonos-discovery\lib\prototypes\Player\getUriType.js:18:10)
    at parseTrackMetadata.then.track (C:\Users\olivi\Downloads\Sonos API remote access\node-sonos-web-controller-master\node_modules\sonos-discovery\lib\models\Player.js:243:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
queue-changed Cuisine
(node:2128) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at isRadio (C:\Users\olivi\Downloads\Sonos API remote access\node-sonos-web-controller-master\node_modules\sonos-discovery\lib\prototypes\Player\getUriType.js:4:14)
    at Player.getUriType (C:\Users\olivi\Downloads\Sonos API remote access\node-sonos-web-controller-master\node_modules\sonos-discovery\lib\prototypes\Player\getUriType.js:18:10)
    at parseTrackMetadata.then.track (C:\Users\olivi\Downloads\Sonos API remote access\node-sonos-web-controller-master\node_modules\sonos-discovery\lib\models\Player.js:243:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by Explorer-OL** [comment]
posted on wrong section... moving to the appropriate one.
