### ISSUE TITLE
Trying to set input on Speakers

### ISSUE THREAD

**Issue by JDogg016** [jishi/node-sonos-http-api#720]
Perhaps I am inputting the command incorrectly:

XXX.XXX.XXX.XXX:5005/Kitchen%20Overhead/setavtransporturi/x-sonos-htastream:RINCON_949F3E22585201400:spdif

I would like this command to change the input back to my TV input.

When I run the command I get this error:
`
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/app/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.setAVTransport (/app/node_modules/sonos-discovery/lib/models/Player.js:727:15)\n    at Object.setAVTransportURI (/app/lib/actions/setavtransporturi.js:3:17)\n    at handleAction (/app/lib/sonos-http-api.js:117:35)\n    at HttpAPI.requestHandler (/app/lib/sonos-http-api.js:94:21)\n    at /app/server.js:50:13\n    at Server.finish (/app/node_modules/node-static/lib/node-static.js:111:13)\n    at finish (/app/node_modules/node-static/lib/node-static.js:170:14)\n    at /app/node_modules/node-static/lib/node-static.js:144:17\n    at `FSReqWrap.oncomplete (fs.js:123:15)"}

I don’t know why.

I also tried:

xxx.xxx.xxx.xxx:5005/Kitchen%20Overhead/setavtransporturi/x-sonos-htastream:RINCON_949F3E22585201400:spdif/Kitchen%20Overhead/play

Same result.

Any assistance would be excellent.

**Comment by r4lv** [comment]
Are you sure about the `%20` (space) in the `x-sonos-htastream` ID? I have an underscore in the transport uri. Maybe you could try

``` text
XXX.XXX.XXX.XXX:5005/Kitchen%20TV/setavtransporturi/x-sonos-htastream:RINCON_949F3E22585201400:spdif
```
