### ISSUE TITLE
join error

### ISSUE THREAD

**Issue by DaveMe81** [jishi/node-sonos-http-api#727]
Hello friends,

I want to join the player "Kueche" to player "Wohnzimmer". So I start: "http://localhost:5005/Kueche/join/Wohnzimmer" with my Raspi.

I got an error message:

{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.setAVTransport (/home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:727:15)\n    at attachTo (/home/pi/node-sonos-http-api-master/lib/actions/group.js:29:17)\n    at Object.joinPlayer [as join] (/home/pi/node-sonos-http-api-master/lib/actions/group.js:21:10)\n    at handleAction (/home/pi/node-sonos-http-api-master/lib/sonos-http-api.js:117:35)\n    at HttpAPI.requestHandler (/home/pi/node-sonos-http-api-master/lib/sonos-http-api.js:94:21)\n    at /home/pi/node-sonos-http-api-master/server.js:50:13\n    at Server.finish (/home/pi/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:111:13)\n    at finish (/home/pi/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:170:14)\n    at /home/pi/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:153:21)"}

What's wrong? start / stop, changing volume, starting radio, ... all works good, but not join.

Thanks for your help.

**Comment by jishi** [comment]
That error is a direct 500 error from the Sonos player. Meaning, it can't actually join it. Are you able to actually join Kueche to Wohnzimmer in the Sonos app? Do you have any paired players?

**Comment by DaveMe81** [comment]
Ok,

Yes, both players are acutally in a group, also in the app. 

I use this join to "reload" default state of my Sonos environment in case there is something missconfigured. 

You are right, the funcion still works. If both players are not in one group: no error messsage.

... while typing this answer, the error never came upp again. I deleted the group, joined again, no error.

I don't know how what is goin on, but now after deleting the group and joining again, all is fine again. Even when the group already exists, no error. Hmm...

**Comment by DaveMe81** [comment]
ok... I got the error again.

It depends on, which player is joining the other.

In the App: When I click on Wohnzimmer and add Kueche to the group: no error.
When I click on Kueche first and adding Wohnzimmer: error message by using the join in the order "Kueche/join/Wohnzimmer".
