### ISSUE TITLE
Cannot connect to Beam HDMI port using "setavtransporturi"

### ISSUE THREAD

**Issue by rexxmundi** [jishi/node-sonos-http-api#756]
Hello,

With reference to:
https://github.com/jishi/node-sonos-http-api/issues/109
https://github.com/jishi/node-sonos-http-api/issues/732

Where I am trying to connect a Play:3 to the HDMI input of a Beam using "setavtransporturi" action, I still get a 500 error.

URL:
http://10.0.0.7:5005/Test/setavtransporturi/x-sonos-htastream:RINCON_48A6B83DCE8101400:spdif

Error:
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/opt/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.setAVTransport (/opt/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:727:15)\n    at Object.setAVTransportURI [as setavtransporturi] (/opt/node-sonos-http-api-master/lib/actions/setavtransporturi.js:3:17)\n    at handleAction (/opt/node-sonos-http-api-master/lib/sonos-http-api.js:117:35)\n    at HttpAPI.requestHandler (/opt/node-sonos-http-api-master/lib/sonos-http-api.js:94:21)\n    at /opt/node-sonos-http-api-master/server.js:50:13\n    at Server.finish (/opt/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:111:13)\n    at finish (/opt/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:170:14)\n    at /opt/node-sonos-http-api-master/node_modules/node-static/lib/node-static.js:144:17\n    at FSReqWrap.oncomplete (fs.js:152:21)"}

State of Beam (where I am trying to get the HDMI input from):
http://10.0.0.7:5005/Office/state

{"volume":12,"mute":false,"equalizer":{"bass":4,"treble":0,"loudness":true,"speechEnhancement":true,"nightMode":false},"currentTrack":{"duration":0,"uri":"x-sonos-htastream:RINCON_48A6B83DCE8101400:spdif","trackUri":"x-sonos-htastream:RINCON_48A6B83DCE8101400:spdif","type":"line_in","stationName":""},"nextTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":""},"trackNo":1,"elapsedTime":39,"elapsedTimeFormatted":"00:00:39","playbackState":"PLAYING","playMode":{"repeat":"none","shuffle":false,"crossfade":false}}

State of Play:3 (where I want to play the input:
http://10.0.0.7:5005/Test/state
{"volume":12,"mute":false,"equalizer":{"bass":4,"treble":0,"loudness":true},"currentTrack":{"artist":"ABC NewsRadio","title":"x-sonosapi-stream:s53432?sid=254&flags=8224&sn=0","albumArtUri":"/getaa?s=1&u=x-sonosapi-stream%3as53432%3fsid%3d254%26flags%3d8224%26sn%3d0","duration":0,"uri":"x-sonosapi-stream:s53432?sid=254&flags=8224&sn=0","trackUri":"x-sonosapi-stream:s53432?sid=254&flags=8224&sn=0","type":"radio","stationName":"ABC NewsRadio","absoluteAlbumArtUri":"http://10.0.0.138:1400/getaa?s=1&u=x-sonosapi-stream%3as53432%3fsid%3d254%26flags%3d8224%26sn%3d0"},"nextTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":""},"trackNo":1,"elapsedTime":0,"elapsedTimeFormatted":"00:00:00","playbackState":"STOPPED","playMode":{"repeat":"none","shuffle":false,"crossfade":false}}

My understanding was that the "setavtransporturi" action should be called with the RINCON from the Beam whilst it is playing from HMDI, which is:
x-sonos-htastream:RINCON_48A6B83DCE8101400:spdif

But this does not work.  Can anybody tell me what I am doing wrong?

Thanks,
Rex

**Comment by hugo-leij** [comment]
I have the same problem. Hopefully there will be a solution for this
