### ISSUE TITLE
Unable to play Spotify track (error 500)

### ISSUE THREAD

**Issue by mattsson** [jishi/node-sonos-http-api#774]
Hi.

I can control my Sonos using `/play`, `/pause`, etc. but when I am trying to play a track using `http://192.168.1.38:5005/Living%20Room/spotify/now/spotify:track:5jgFfDIR6FR0gvlA56Nakr` on a Sonos Play:1 running S2 v. 12.0.3, it gives me this error:

```
Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control at Object.invoke (/Users/marcusmattsson/Scripts/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
at Player.trackSeek (/Users/marcusmattsson/Scripts/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:552:15) 
at player.coordinator.addURIToQueue.then (/Users/marcusmattsson/Scripts/node-sonos-http-api/lib/actions/spotify.js:38:56) 
at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by mattsson** [comment]
It works after rebooting the Sonos device.
