### ISSUE TITLE
npm start Issue on rasberri pi

### ISSUE THREAD

**Issue by ChiPaulMichaels** [jishi/node-sonos-http-api#78]
Trying to get this going on my RPi2. 
I ran npm start and got the following error:

```
pi@raspberrypi ~ $ npm start

> sonos-http-api@0.16.0 start /home/pi
> node server.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/home/pi/server.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

npm ERR! Linux 4.1.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! sonos-http-api@0.16.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonos-http-api@0.16.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the sonos-http-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-http-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
```

Any idea what's going on? Thanks in advance.

**Comment by ChiPaulMichaels** [comment]
Nevermind, I figured out the issue.

**Comment by JerCoke** [comment]
@ChiPaulMichaels What was your solution?  I'm experiencing the same issue.  Thanks in advance!

**Comment by ChiPaulMichaels** [comment]
It was just me not knowing what I was doing apparently. 

I ended up using forever to make sure that it's always running, and then added that to /etc/rc.local so it starts up on boot
Specifically I added the following to the file:
```
forever start '/home/pi/node-sonos-http-api/server.js' &
```
