### ISSUE TITLE
Getting this error when using HTTP command to play a preset

### ISSUE THREAD

**Issue by pcgirl** [jishi/node-sonos-http-api#782]
{"status":"error","error":"Cannot read property 'avTransportUri' of undefined","stack":"TypeError: Cannot read property 'avTransportUri' of undefined\n    at /app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:55:18\n    at Array.reduce (<anonymous>)\n    at groupWithCoordinator (/app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:53:6)\n    at /app/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:113:12"}

**Comment by jishi** [comment]
Are you running S2?

**Comment by pcgirl** [comment]
Sonos 2?  Probably.  It updated a couple of times lately.

Thanks,
Jane Johnson
________________________________
