### ISSUE TITLE
After updating all node modules, sonos http server throws error on npm start

### ISSUE THREAD

**Issue by jsiegenthaler** [jishi/node-sonos-http-api#805]
After updating all node modules, sonos http server throws error on npm start:

```
pi@raspberrypi:~/node-sonos-http-api-master $ npm start

> sonos-http-api@1.6.9 start
> node server.js

2021-06-04T17:13:46.021Z INFO Could not find file /home/pi/node-sonos-http-api-m                                                                              aster/settings.json
2021-06-04T17:13:46.265Z INFO Presets loaded: {
  example: {
    players: [
      { roomName: 'Bathroom', volume: 10 },
      { roomName: 'Kitchen', volume: 10 },
      { roomName: 'Office', volume: 10 },
      { roomName: 'Bedroom', volume: 10 },
      { roomName: 'TV Room', volume: 15 }
    ],
    playMode: { shuffle: true, repeat: 'all', crossfade: false },
    pauseOthers: false
  }
}
/home/pi/node-sonos-http-api-master/lib/tts-providers/microsoft.js:11
const xmlEntities = new XmlEntities();
                    ^

TypeError: XmlEntities is not a constructor
    at Object.<anonymous> (/home/pi/node-sonos-http-api-master/lib/tts-providers                                                                              /microsoft.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/pi/node-sonos-http-api-master/node_modules/sonos-discovery/lib/help                                                                              ers/require-dir.js:18:20
    at Array.forEach (<anonymous>)
    at module.exports (/home/pi/node-sonos-http-api-master/node_modules/sonos-di                                                                              scovery/lib/helpers/require-dir.js:17:6)
    at Object.<anonymous> (/home/pi/node-sonos-http-api-master/lib/helpers/try-d                                                                              ownload-tts.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/node-sonos-http-api-master/lib/actions/say.j                                                                              s:6:24)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
pi@raspberrypi:~/node-sonos-http-api-master $

```

**Comment by jsiegenthaler** [comment]
I solved it, it was a local pi issue. Closing this issue.
