### ISSUE TITLE
Preset playing favorite error

### ISSUE THREAD

**Issue by sorenkristensen80** [jishi/node-sonos-http-api#816]
Hi,

My knowledge level is "newbie-level". Been using the node-sonos for a while and play a radio-station as a favorite stated in my preset-file (/preset/my_presets/favorite), but a few days ago it started failing - giving this error, when attempting to run it in browser:

{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.setAVTransport (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:727:15)\n    at /home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithFavorite.js:45:19\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}

Anybody speak/understand this?

**Comment by sorenkristensen80** [comment]
Apparently this was due to an error in Sonos app when attempting to start radiostation as favorites. Removing and re-adding them worked.
