### ISSUE TITLE
"say" Error: http request timed out

### ISSUE THREAD

**Issue by crissmil** [jishi/node-sonos-http-api#882]
Hi jishi,
Thanks again for your api which I'm using for so many years...
I have it now installed on my macbook (working on a project away from home)

All below cmd are working:
curl 'http://localhost:5005/Apple%20TV%20Sonos/volume/10'
curl 'http://localhost:5005/Apple%20TV%20Sonos/play'
curl 'http://localhost:5005/Apple%20TV%20Sonos/pause'
....

But below cmd is not working and throwing below error:
curl 'http://localhost:5005/Apple%20TV%20Sonos/say/test'

2024-01-08T15:49:58.111Z INFO http server listening on 0.0.0.0 port 5005
2024-01-08T15:50:12.072Z ERROR 
  Error: http request timed out
    at Object.invoke (/Users/cristi/Sonos_API/node-sonos-http-api-master/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)
    at Player.becomeCoordinatorOfStandaloneGroup (/Users/cristi/Sonos_API/node-sonos-http-api-master/node_modules/sonos-discovery/lib/models/Player.js:738:15)
    at /Users/cristi/Sonos_API/node-sonos-http-api-master/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:109:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

It is waiting first to download audio file then comes above error.
I am using Microsoft tts with same credentials from home, in fact I've copied the same settings.json file from home raspi.
Your help is much appreciated as usual!

**Comment by crissmil** [comment]
well... I found the problem. It was my internet connection. I am sailing and was initially on satelite connection (maybe behind some firewall rules) when got this issue. After approaching land and connected to 4G mobile network, everything is working. Thanks again for your great work!
