### ISSUE TITLE
just update and load error?

### ISSUE THREAD

**Issue by robertw** [jishi/node-sonos-http-api#89]
> sonos-http-api@0.17.0 start /home/pi/sonosapi
> node server.js

/home/pi/sonosapi/lib/sonos-http-api.js:94
        type,
            ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/sonosapi/server.js:5:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by robertw** [comment]
just updated to 4.o node on pi and all is well thanks anyway
