### ISSUE TITLE
Failed to Execute Start Script

### ISSUE THREAD

**Issue by erodenberg-esri** [jishi/node-sonos-http-api#890]
I'm running into an issue getting the API started.  The log file is saying that it failed to execute the start script.  Here is a dump of my log: 

```
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.24.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
7 info using npm@5.8.0
8 info using node@v10.24.0
9 verbose run-script [ 'prestart', 'start', 'poststart' ]
10 info lifecycle sonos-http-api@1.6.9~prestart: sonos-http-api@1.6.9
11 info lifecycle sonos-http-api@1.6.9~start: sonos-http-api@1.6.9
12 verbose lifecycle sonos-http-api@1.6.9~start: unsafe-perm in lifecycle true
13 verbose lifecycle sonos-http-api@1.6.9~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/node-sonos-http-api/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/$
14 verbose lifecycle sonos-http-api@1.6.9~start: CWD: /home/pi/node-sonos-http-api
15 silly lifecycle sonos-http-api@1.6.9~start: Args: [ '-c', 'node server.js' ]
16 silly lifecycle sonos-http-api@1.6.9~start: Returned: code: 1  signal: null
17 info lifecycle sonos-http-api@1.6.9~start: Failed to exec start script
18 verbose stack Error: sonos-http-api@1.6.9 start: `node server.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
18 verbose stack     at EventEmitter.emit (events.js:198:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:198:13)
18 verbose stack     at maybeClose (internal/child_process.js:982:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid sonos-http-api@1.6.9
20 verbose cwd /home/pi/node-sonos-http-api
21 verbose Linux 4.19.97-v7+
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
23 verbose node v10.24.0
24 verbose npm  v5.8.0
25 error code ELIFECYCLE
26 error errno 1
27 error sonos-http-api@1.6.9 start: `node server.js`
27 error Exit status 1
28 error Failed at the sonos-http-api@1.6.9 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

**Comment by jishi** [comment]
Try running it with node directly (node server.js) and see what it says.

**Comment by erodenberg-esri** [comment]
Jimmy,

Here you go… I think it is saying that it can find the Axios library. Do I have that right?

***@***.***:~/node-sonos-http-api $ node server.js
2024-05-10T20:13:58.783Z INFO Presets loaded: { example:
   { players:
      [ { roomName: 'Bathroom', volume: 10 },
        { roomName: 'Kitchen', volume: 10 },
        { roomName: 'Office', volume: 10 },
        { roomName: 'Bedroom', volume: 10 },
        { roomName: 'TV Room', volume: 15 } ],
     playMode: { shuffle: true, repeat: 'all', crossfade: false },
     pauseOthers: false } }
/home/pi/node-sonos-http-api/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/node-sonos-http-api/node_modules/elevenlabs-node/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/node-sonos-http-api/lib/tts-providers/elevenlabs.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by jishi** [comment]
Looks like the axios lib that is installed is an esm module. I wouldn't
expect the package-lock.json to include an esm-version, but maybe some
references there are incompatible with node 10.

Either update to node 18 which should support esm modules, or find a
version of axios that doesn't compile as esm (basically, <1.0.0, 0.27.2
seems to be the last one).

Not sure it would work though.

**Comment by erodenberg-esri** [comment]
Updated to Node 18.20.2… all is working,  Thanks.
