### ISSUE TITLE
Strange preset problem with Status 500

### ISSUE THREAD

**Issue by jasonthefirs** [jishi/node-sonos-http-api#904]
So I've been running this API for years and I adore it and it's worked mostly flawlessly.

Ran into a very weird issue lately that I cannot seem to untangle, so here I am. 

I have three distinct presets that I use. One is for all the Sonos speakers in the house, one is for the speakers on the first floor, one for the speakers on the second floor. The 'all' and 'downstairs' presets work just fine, but the 'upstairs' preset gives me this error:

> "status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.play (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:446:15)\n    at /home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/SonosSystem/applyPreset.js:153:46\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

What's especially weird to me is that all of the speakers in the 'upstairs' preset are also in the 'all' preset, and the 'all' preset is working, so I can't figure out what could be causing the issue with the 'upstairs' preset. I've deleted and re-entered the json file several times, copying and pasting from the functional preset to make sure the syntax is right, and still getting that error... 

Any advice on how to get this preset working again would be much appreciated, thank you!

**Comment by jishi** [comment]
The players doesn't give much info on why the control calls fail in these instances. Normally, this is instructions to the players that are invalid due to the current state, like setting "random" playback when you are streaming a radio channel, as an example. 

Try to check the difference in source, and various playback options compared to your "all" preset and see if something differs.
